In [1]:
import os
import json

import purify_functions

In [2]:
with open("purified_child_to_par_wiki.json",'r') as fd:
    df=json.load(fd)

In [3]:
df[0]

{'pageid': 4210106,
 'url': 'https://en.wikipedia.org/wiki/Abraham_Silberschatz',
 'links': ['ACM Fellow',
  'Bell Labs',
  'C. Mohan',
  'Computer Science',
  'Computer scientist',
  'Database System Concepts',
  'Database systems',
  'Doctoral advisor',
  'Google Scholar',
  'Haifa, Israel',
  'ISNI (identifier)',
  'Operating systems',
  'RERO (identifier)',
  'Raghu Ramakrishnan',
  'Research',
  'SUDOC (identifier)',
  'State University of New York',
  'Stony Brook University',
  'University of texas at austin',
  'VIAF (identifier)',
  'Yale University'],
 'aliases': ['Avi Silberschatz'],
 'label': 'Abraham Silberschatz',
 'title': 'Abraham_Silberschatz',
 'image': 'Avi silberschatz.jpg',
 'backlinks': ['Database',
  'Windows 2000',
  'Process (computing)',
  'Program counter',
  'Memory management',
  'Scheduling (computing)',
  'Round-robin scheduling',
  'Two-phase locking',
  'Join (SQL)',
  'Page table',
  'Slab allocation',
  'Multivalued dependency',
  'List of Stony Brook University people',
  'Global serializability',
  'Kernel (operating system)',
  'C. Mohan',
  'Talk:Abraham Silberschatz',
  'User:Tony Sidaway/Living people/tranche 082',
  'User:Dingo1729/History of commitment ordering',
  'Database System Concepts',
  'User:Ibon.coria/sandbox',
  "Wikipedia:Administrators' noticeboard/IncidentArchive822",
  'User:Rebone System/sandbox',
  'User:H@r@ld/opensyllabus',
  'List of fellows of the Association for Computing Machinery',
  'User talk:Tom29739/Archive 27',
  'User:Oshwah/TalkPageArchives/2017-06',
  'User talk:Tom29739/Archive 30',
  'User talk:Tom29739/Archive 32',
  'User talk:Tom29739/Archive 34',
  'User talk:Tom29739/Archive 36',
  'User talk:Tom29739/Archive 38',
  'User talk:Tom29739/Archive 39',
  'User talk:Tom29739/Archive 43',
  'User talk:Tom29739/Archive 45',
  'File:Database System Concepts.jpg'],
 'categories': ['Category:American computer scientists',
  'Category:American computer specialist stubs',
  'Category:Fellow Members of the IEEE',
  'Category:Fellows of the Association for Computing Machinery',
  'Category:Living people',
  'Category:Stony Brook University alumni',
  'Category:Yale University faculty'],
 'ire_person_name': 'Abraham Silberschatz',
 'ire_wiki_id': 0,
 'name': 'Avi Silberschatz',
 'field': '[[Computer Science]]',
 'work_institution': '[[Yale University]]',
 'alma_mater': '[[Stony Brook University]]<br />[[Yale University]]',
 'doctoral_advisor': 'Arthur Bernstein<br>Richard Kieburtz',
 'doctoral_students': '[[C. Mohan]]<br>[[Raghu Ramakrishnan]]',
 'known_for': '[[database systems]]<br>[[operating systems]]',
 'prizes': 'ACM Fellow<br>IEEE Fellow<br>AAAS Fellow<br>IEEE Taylor L. Booth Education Award (2002)<br>ACM Karl V. Karlstrom Outstanding Educator Award (1998)<br>ACM SIGMOD Contribution Award (1997)<br> 2019 VLDB Test of Time Award',
 'website': 'http://www.cs.yale.edu/~avi/',
 'sex or gender (P21)': 'male (Q6581097)',
 'occupation (P106)': ['computer scientist (Q82594)', 'engineer (Q81096)'],
 'given name (P735)': 'Abraham (Q17997608)',
 'member of (P463)': 'Institute of Electrical and Electronics Engineers (Q131566)',
 'employer (P108)': 'Yale University (Q49112)',
 'country of citizenship (P27)': 'United States of America (Q30)',
 'educated at (P69)': ['Stony Brook University (Q969850)',
  'State University of New York (Q1140241)',
  'IDF Junior Command Preparatory Boarding School (Q7063325)'],
 'Library of Congress authority ID (P244)': 'n82162524',
 'Mathematics Genealogy Project ID (P549)': '94554',
 'languages spoken, written or signed (P1412)': 'English (Q1860)',
 'award received (P166)': ['ACM Fellow (Q18748039)', 'IEEE Fellow (Q111734)'],
 'doctoral student (P185)': ['C. Mohan (Q5006716)',
  'Raghu Ramakrishnan (Q7282986)',
  'Rajeev Rastogi (Q15995420)',
  'Donald Spencer Fussell (Q102129368)',
  'Iyer Venkateshwaran Ramakrishnan (Q102157550)',
  'Sharad Mehrotra (Q102196909)',
  'Samuel Lycurgus Grier, Jr. (Q102300750)',
  'Sumit Ganguly (Q102300751)',
  'Ernest Samuel Cohen (Q102300752)',
  'Khien Mien Chew (Q102300753)',
  'Banu Rahime Ozden (Q102300754)',
  'Robert Lee Read (Q102300755)'],
 'student (P802)': 'Kenneth Seals-Nutt (Q47487399)',
 'place of birth (P19)': 'Haifa (Q41621)',
 'official website (P856)': 'http://www.cs.yale.edu/~avi/',
 'WorldCat Identities ID (P7859)': 'lccn-n82162524',
 'doctoral advisor (P184)': ['Arthur Jay Bernstein (Q102077480)',
  'Richard Kieburtz (Q68622015)'],
 'Freebase ID (P646)': '/m/0bq3td',
 'date of birth (P569)': '+1947-05-01T00:00:00Z'}

In [4]:
samples=dict()

In [5]:
for curr_elem in df:
    for curr_key, curr_val in curr_elem.items():
        if curr_key not in samples:
            samples[curr_key]=curr_val

In [6]:
attribute_name="backlinks"
samples[attribute_name]

['Database',
 'Windows 2000',
 'Process (computing)',
 'Program counter',
 'Memory management',
 'Scheduling (computing)',
 'Round-robin scheduling',
 'Two-phase locking',
 'Join (SQL)',
 'Page table',
 'Slab allocation',
 'Multivalued dependency',
 'List of Stony Brook University people',
 'Global serializability',
 'Kernel (operating system)',
 'C. Mohan',
 'Talk:Abraham Silberschatz',
 'User:Tony Sidaway/Living people/tranche 082',
 'User:Dingo1729/History of commitment ordering',
 'Database System Concepts',
 'User:Ibon.coria/sandbox',
 "Wikipedia:Administrators' noticeboard/IncidentArchive822",
 'User:Rebone System/sandbox',
 'User:H@r@ld/opensyllabus',
 'List of fellows of the Association for Computing Machinery',
 'User talk:Tom29739/Archive 27',
 'User:Oshwah/TalkPageArchives/2017-06',
 'User talk:Tom29739/Archive 30',
 'User talk:Tom29739/Archive 32',
 'User talk:Tom29739/Archive 34',
 'User talk:Tom29739/Archive 36',
 'User talk:Tom29739/Archive 38',
 'User talk:Tom29739/Archive 39',
 'User talk:Tom29739/Archive 43',
 'User talk:Tom29739/Archive 45',
 'File:Database System Concepts.jpg']

In [7]:
!ls

all_funcs.py			      oct_explore_attributes.ipynb
all_wiki_attributes_freq_sorted.json  oct_fetch_aliases.ipynb
child_to_par_wiki.json		      oct_infobox_keys_set.txt
cleaned_merged_par_child_wiki.json    oct_prelim_wikidata_version.json
inspect_perform.json		      purified_child_to_par_wiki.json
nice_birth_date_mapping.json	      purify_functions.py
nov_explore_wikidata.ipynb	      __pycache__
oct_alias_mapping.json		      temp_mapping.json
oct_create_prelim_wiki_data.ipynb     test_purify_functions.ipynb
oct_exp.ipynb			      useful_attributes.json

In [8]:
with open("./useful_attributes.json",'r') as fd:
    lst=json.load(fd)

In [9]:
detailed_arr=[]
for curr_elem in lst:
    detailed_obj=dict()
    detailed_obj['attr_name']=curr_elem[0]
    detailed_obj['freq']=curr_elem[1]
    detailed_obj['sample']=samples[curr_elem[0]]
    detailed_obj['parent_attr']=""
    detailed_obj['func']=None
    detailed_arr.append(detailed_obj)

In [10]:
with open("./temp_mapping.json", 'w') as fd:
    json.dump(detailed_arr,fd, indent=4 )

In [11]:
%load_ext autoreload
%autoreload 2

In [12]:
from all_funcs import *

In [13]:
purify_backlinks

In [14]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [15]:
purify_categories(samples['categories'])

['American computer scientists',
 'American computer specialist stubs',
 'Fellow Members of the IEEE',
 'Fellows of the Association for Computing Machinery',
 'Living people',
 'Stony Brook University alumni',
 'Yale University faculty']

In [16]:
purify_categories

In [17]:
tc="{{startplainlist|class|=|nowrap}} * [[St. John's College, Oxford]] (no degree)\n* [[California Institute of Technology]]<br>(PhD, 1980) {{endplainlist}}"

In [18]:
import re
def get_univs_from_alma_mater(curr_str):
    arr=re.findall('\[\[.*\]\]', curr_str)
    arr=[x.replace("[","") for x in arr]
    arr=[x.replace("]","") for x in arr]
    return arr

In [19]:
get_univs_from_alma_mater(tc)

["St. John's College, Oxford", 'California Institute of Technology']

In [20]:
dob_tc="+1947-05-01T00:00:00Z"

In [21]:
birth_mapping_arr=[]

In [22]:
for curr_elem in df:
    if 'birth_date' in curr_elem:
        exp=curr_elem['birth_date']
        got=purify_birth_date(exp)
        print(f"{exp} -> {got}")
        birth_mapping_arr.append({"input":exp, "output":got})

{{Birth date|1917|3|7}} -> {'year': 1917, 'month': 3, 'day': 7}
{{birth year and age|1964}} -> {'year': 1964, 'month': None, 'day': None}
{{Birth date|1938|11|13|df|=|yes}} -> {'year': 1938, 'month': 11, 'day': 13}
{{Birth date and age|1978|5|3|mf|=|y}} -> {'year': 1978, 'month': 5, 'day': 3}
14 September 1769 -> {'year': 1769, 'month': 9, 'day': 14}
{{Birth date and age|1950|07|18}} -> {'year': 1950, 'month': 7, 'day': 18}
{{birth date and age|df|=|yes|1959|8|29}} -> {'year': 1959, 'month': 8, 'day': 29}
{{birth date and age|mf|=|y|1942|1|6}} -> {'year': 1942, 'month': 1, 'day': 6}
{{birth year and age|1936}} -> {'year': 1936, 'month': None, 'day': None}
{{Birth year and age|1955}} -> {'year': 1955, 'month': None, 'day': None}
{{Birth date|1953|10|8}} -> {'year': 1953, 'month': 10, 'day': 8}
{{birth date|1924|9|3}} -> {'year': 1924, 'month': 9, 'day': 3}
{{birth date and age|1947|11|16}} -> {'year': 1947, 'month': 11, 'day': 16}
{{Birth date and age|1957|4|2|df|=|y}} -> {'year': 1957, 'month': 4, 'day': 2}
{{Birth date|df|=|y|1934|5|19}} -> {'year': 1934, 'month': 5, 'day': 19}
{{Birth date and age|df|=|yes|1947|12|06}} -> {'year': 1947, 'month': 12, 'day': 6}
{{birth date |1932|2|29|mf|=|y}} -> {'year': 1932, 'month': 2, 'day': 29}
{{Birth date|1924|03|24}} -> {'year': 1924, 'month': 3, 'day': 24}
{{Birth date and age|1936|11|16|mf|=|y}} -> {'year': 1936, 'month': 11, 'day': 16}
{{birth date and age|1964|03|15}} -> {'year': 1964, 'month': 3, 'day': 15}
{{birth date and age|1944|06|05}} -> {'year': 1944, 'month': 6, 'day': 5}
{{birth year and age|1958}} -> {'year': 1958, 'month': None, 'day': None}
{{birth date and age|1949|8|24|df|=|y}} -> {'year': 1949, 'month': 8, 'day': 24}
{{birth-date and age|December 1948}} -> {'year': 1948, 'month': None, 'day': None}
{{birth date|1909|01|05}} -> {'year': 1909, 'month': 1, 'day': 5}
{{Birth date and age|1978|10|26|df|=|y}} -> {'year': 1978, 'month': 10, 'day': 26}
{{Birth date and age|1948|01|19}} -> {'year': 1948, 'month': 1, 'day': 19}
{{Birth date and age|1967|10|28}} -> {'year': 1967, 'month': 10, 'day': 28}
February 11, 1945 -> {'year': 1945, 'month': 2, 'day': 11}
{{birth date and age|1957|8|21}} -> {'year': 1957, 'month': 8, 'day': 21}
1950 -> {'year': 1950, 'month': None, 'day': None}
{{birth date and age|df|=|yes|1959|7|28}} -> {'year': 1959, 'month': 7, 'day': 28}
{{Birth date and age|1939|08|17}} -> {'year': 1939, 'month': 8, 'day': 17}
{{birth year and age|1980}} -> {'year': 1980, 'month': None, 'day': None}
{{Birth date and age|1938|12|16|mf|=|yes}} -> {'year': 1938, 'month': 12, 'day': 16}
{{Birth year and age|1949}} -> {'year': 1949, 'month': None, 'day': None}
{{Birth date|df|=|yes|1952|12|28}} -> {'year': 1952, 'month': 12, 'day': 28}
{{Birth year and age|1972|1}} -> {'year': 1972, 'month': None, 'day': None}
{{birth year and age |1953}} -> {'year': 1953, 'month': None, 'day': None}
{{birth date|1917|12|07}} -> {'year': 1917, 'month': 12, 'day': 7}
{{Birth date|1918|8|16}} -> {'year': 1918, 'month': 8, 'day': 16}
January 8, 1917 -> {'year': 1917, 'month': 1, 'day': 8}
{{Birth date and age|1944|07|21|df|=|y}} -> {'year': 1944, 'month': 7, 'day': 21}
{{Birth date and age|1959|03|23}} -> {'year': 1959, 'month': 3, 'day': 23}
{{Birth date|1930|05|11|df|=|yes}} -> {'year': 1930, 'month': 5, 'day': 11}
{{birth date and age|1938|1|10}} -> {'year': 1938, 'month': 1, 'day': 10}
{{Birth year and age|1981}} -> {'year': 1981, 'month': None, 'day': None}
{{Birth date and age|1933|6|5}} -> {'year': 1933, 'month': 6, 'day': 5}
{{birth date and age|1964|9|13|df|=|y}} -> {'year': 1964, 'month': 9, 'day': 13}
{{birth date|1962|01|01}} -> {'year': 1962, 'month': 1, 'day': 1}
{{birth year and age|1943}} -> {'year': 1943, 'month': None, 'day': None}
{{Birth date and age|1939|10|7|mf|=|y}} -> {'year': 1939, 'month': 10, 'day': 7}
{{Birth date|1918|08|26}} -> {'year': 1918, 'month': 8, 'day': 26}
{{Birth date and age|df|=|yes|1972|03|31}} -> {'year': 1972, 'month': 3, 'day': 31}
{{birth date and age|1973|06|11}} -> {'year': 1973, 'month': 6, 'day': 11}
1946 -> {'year': 1946, 'month': None, 'day': None}
{{birth year and age|1970}} -> {'year': 1970, 'month': None, 'day': None}
1975 -> {'year': 1975, 'month': None, 'day': None}
{{Birth date and age|1949|06|29|mf|=|yes}} -> {'year': 1949, 'month': 6, 'day': 29}
{{birth date|df|=|y|1925|1|24}} -> {'year': 1925, 'month': 1, 'day': 24}
{{Birth date|1937|12|09}} -> {'year': 1937, 'month': 12, 'day': 9}
{{b-da|October 23, 1960}} -> {'year': 1960, 'month': 10, 'day': 23}
{{bya|1950}} -> {'year': 1950, 'month': None, 'day': None}
{{Birth date and age|1953|1|19|mf|=|yes}} -> {'year': 1953, 'month': 1, 'day': 19}
{{Birth date and age|1960|10|28|mf|=|y}} -> {'year': 1960, 'month': 10, 'day': 28}
{{Birth date|df|=|yes|1927|08|24}} -> {'year': 1927, 'month': 8, 'day': 24}
{{Birth date|df|=|yes|1923|11|11}} -> {'year': 1923, 'month': 11, 'day': 11}
{{birth date and age|1966|8|30|mf|=|y}} -> {'year': 1966, 'month': 8, 'day': 30}
{{birth date and age|df|=|yes|1962|11|19}} -> {'year': 1962, 'month': 11, 'day': 19}
{{birth date and age|1954|9|17}} -> {'year': 1954, 'month': 9, 'day': 17}
{{Birth date and age|1946|9|6}} -> {'year': 1946, 'month': 9, 'day': 6}
{{Birth date|1928|1|27}} -> {'year': 1928, 'month': 1, 'day': 27}
{{Birth date and age|1938|10|22}} -> {'year': 1938, 'month': 10, 'day': 22}
{{birth date and age|1963|11|10}} -> {'year': 1963, 'month': 11, 'day': 10}
{{Birth date|1935|05|20|df|=|yes}} -> {'year': 1935, 'month': 5, 'day': 20}
{{birth year and age|1964}} -> {'year': 1964, 'month': None, 'day': None}
{{birth date and age|mf|=|yes|1960|05|03}} -> {'year': 1960, 'month': 5, 'day': 3}
1942 -> {'year': 1942, 'month': None, 'day': None}
{{Birth year and age|1957}} -> {'year': 1957, 'month': None, 'day': None}
{{birth date|1959|9|21|mf|=|y}} -> {'year': 1959, 'month': 9, 'day': 21}
{{birth date and age|1956|9|19}} -> {'year': 1956, 'month': 9, 'day': 19}
{{Birth date and age|1944|07|21|df|=|y}} -> {'year': 1944, 'month': 7, 'day': 21}
{{birth date|df|=|y|1815|12|10}} -> {'year': 1815, 'month': 12, 'day': 10}
{{Birth date and age|1931|04|19|mf|=|y}} -> {'year': 1931, 'month': 4, 'day': 19}
{{birth date and age|1952|08|19}} -> {'year': 1952, 'month': 8, 'day': 19}
{{Birth date|1933|1|8}} -> {'year': 1933, 'month': 1, 'day': 8}
{{Birth year and age|1932}} -> {'year': 1932, 'month': None, 'day': None}
{{Birth year and age|1961}} -> {'year': 1961, 'month': None, 'day': None}
{{Birth year and age|1965}} {{citation needed|date|=|July 2013}} -> {'year': 1965, 'month': None, 'day': None}
{{birth date|1914|9|9|df|=|y}} -> {'year': 1914, 'month': 9, 'day': 9}
1942 -> {'year': 1942, 'month': None, 'day': None}
{{Birth date and age|1941|5|30}} -> {'year': 1941, 'month': 5, 'day': 30}
{{Birth year and age|1967}} -> {'year': 1967, 'month': None, 'day': None}
{{birth date and age|1992|01|24}} -> {'year': 1992, 'month': 1, 'day': 24}
{{birth date|1936|11|5}} -> {'year': 1936, 'month': 11, 'day': 5}
{{Birth date and age|1952|9|16|df|=|yes}} -> {'year': 1952, 'month': 9, 'day': 16}
{{birth year and age|1964}} -> {'year': 1964, 'month': None, 'day': None}
{{birth date and age|1956|10|28}} -> {'year': 1956, 'month': 10, 'day': 28}
{{birth date and age|df|=|yes|1957|10|7}} -> {'year': 1957, 'month': 10, 'day': 7}
{{birth year and age|1960}} -> {'year': 1960, 'month': None, 'day': None}
{{Birth date|1924|03|27}} -> {'year': 1924, 'month': 3, 'day': 27}
1962 -> {'year': 1962, 'month': None, 'day': None}
{{Birth date and age|df|=|yes|1948|2|5}} -> {'year': 1948, 'month': 2, 'day': 5}
{{birth date and age|1964|12|29|df|=|y}} -> {'year': 1964, 'month': 12, 'day': 29}
{{Birth date|1936|6|26}} -> {'year': 1936, 'month': 6, 'day': 26}
May 1967 -> {'year': 1967, 'month': 5, 'day': None}
September 9, 1921 -> {'year': 1921, 'month': 9, 'day': 9}
{{birth date and age |1957 |9 |23}} -> {'year': 1957, 'month': 9, 'day': 23}
{{birth date and age|1981|5|14|df|=|y}} -> {'year': 1981, 'month': 5, 'day': 14}
{{birth date |1921|3|11|mf|=|y}} -> {'year': 1921, 'month': 3, 'day': 11}
{{birth date and age|1951|11|20}} -> {'year': 1951, 'month': 11, 'day': 20}
{{Birth date and age|1952|02|18}} -> {'year': 1952, 'month': 2, 'day': 18}
{{birth date|1953|12|17}} -> {'year': 1953, 'month': 12, 'day': 17}
{{birth date|1953|12|3|mf|=|y}} -> {'year': 1953, 'month': 12, 'day': 3}
{{Birth year and age|1955}} -> {'year': 1955, 'month': None, 'day': None}
{{Birth date and age|1968|08|27}} -> {'year': 1968, 'month': 8, 'day': 27}
2 November 1944 -> {'year': 1944, 'month': 11, 'day': 2}
{{Birth year and age|1983}} -> {'year': 1983, 'month': None, 'day': None}
1985 -> {'year': 1985, 'month': None, 'day': None}
{{Birth date and age|1974|9|20|mf|=|y}} -> {'year': 1974, 'month': 9, 'day': 20}
{{Birth date and age|1967|2|14|df|=|yes}} -> {'year': 1967, 'month': 2, 'day': 14}
{{birth date and age|1963|01|25}} -> {'year': 1963, 'month': 1, 'day': 25}
{{Birth date and age|1977|02|27}} -> {'year': 1977, 'month': 2, 'day': 27}
{{birth date |1964|07|29}} -> {'year': 1964, 'month': 7, 'day': 29}

{{birth date and age|1967|11|01}} -> {'year': 1967, 'month': 11, 'day': 1}
{{birth date|1931|02|05|df|=|yes}} -> {'year': 1931, 'month': 2, 'day': 5}
{{Birth date and age|1946|02|10|df|=|y}} -> {'year': 1946, 'month': 2, 'day': 10}
{{birth date|1913|12|17}} -> {'year': 1913, 'month': 12, 'day': 17}
{{birth date|1951|05|08|df|=|y}} -> {'year': 1951, 'month': 5, 'day': 8}
{{birth year and age|1954}} -> {'year': 1954, 'month': None, 'day': None}
{{Birth date and age|1983|4|1}} -> {'year': 1983, 'month': 4, 'day': 1}
{{birth date|1925|3|11}} -> {'year': 1925, 'month': 3, 'day': 11}
{{birth date|1927|8|9}} -> {'year': 1927, 'month': 8, 'day': 9}
{{birth date|1936|3|25}} -> {'year': 1936, 'month': 3, 'day': 25}
{{birth date and age|1955|10|19}} -> {'year': 1955, 'month': 10, 'day': 19}
{{birth date and age|1944|03|18|mf|=|y}} -> {'year': 1944, 'month': 3, 'day': 18}
{{birth date|1926|5|31}} -> {'year': 1926, 'month': 5, 'day': 31}
{{b-da|May 28, 1959}} -> {'year': 1959, 'month': 5, 'day': 28}
{{birth date and age|df|=|yes|1945|08|22}} -> {'year': 1945, 'month': 8, 'day': 22}
{{Birth date and age|1949|06|24|df|=|y}} -> {'year': 1949, 'month': 6, 'day': 24}
{{Birth date and age|df|=|yes|1937|6|13}} -> {'year': 1937, 'month': 6, 'day': 13}
{{birth date and age |1975|1|26}} -> {'year': 1975, 'month': 1, 'day': 26}
August 16, 1946 -> {'year': 1946, 'month': 8, 'day': 16}
{{birth date|1932|08|04}} -> {'year': 1932, 'month': 8, 'day': 4}
{{birth date and age|1943|12|23}} -> {'year': 1943, 'month': 12, 'day': 23}
{{Birth date|1936|06|08|mf|=|y}} -> {'year': 1936, 'month': 6, 'day': 8}
{{birth date and age |1947|9|4|mf|=|y}} -> {'year': 1947, 'month': 9, 'day': 4}
{{Birth date|1935|2|15|mf|=|yes}} -> {'year': 1935, 'month': 2, 'day': 15}
{{Birth date and age|1946|04|07}} -> {'year': 1946, 'month': 4, 'day': 7}
{{birth date and age|1934|02|15|df|=|y}} -> {'year': 1934, 'month': 2, 'day': 15}
{{Birth date and age|df|=|yes|1968|12|18}} -> {'year': 1968, 'month': 12, 'day': 18}
{{abbr|c.|circa}} {{birth year and age|1948}} -> {'year': 1948, 'month': None, 'day': None}
{{b-da|September 14, 1963}} -> {'year': 1963, 'month': 9, 'day': 14}
{{birth date and age|1946|12|20}} -> {'year': 1946, 'month': 12, 'day': 20}
{{birth date|mf|=|yes|1911|08|18}} -> {'year': 1911, 'month': 8, 'day': 18}
{{birth date and age|mf|=|yes|1935|12|25}} -> {'year': 1935, 'month': 12, 'day': 25}
December 1966 -> {'year': 1966, 'month': 12, 'day': None}
{{Birth date|df|=|y|1912|6|23}} -> {'year': 1912, 'month': 6, 'day': 23}
{{birth date and age|1981|2|28}} -> {'year': 1981, 'month': 2, 'day': 28}
{{birth date and age|1959|12|1|mf|=|yes}} -> {'year': 1959, 'month': 12, 'day': 1}
{{Birth date|1941|4|22|mf|=|y}} -> {'year': 1941, 'month': 4, 'day': 22}
{{Birth date|1934|05|08}} -> {'year': 1934, 'month': 5, 'day': 8}
{{birth date and age|df|=|yes|1971|08|16}} -> {'year': 1971, 'month': 8, 'day': 16}
{{birth date and age |1955|01|19}} -> {'year': 1955, 'month': 1, 'day': 19}
{{birth-date and age|1991}} -> {'year': 1991, 'month': None, 'day': None}
{{Birth date|1927|3|19|mf|=|y}} -> {'year': 1927, 'month': 3, 'day': 19}
{{birth date|1927|03|08}} -> {'year': 1927, 'month': 3, 'day': 8}
{{Birth date and age|1958|09|05|df|=|yes}} -> {'year': 1958, 'month': 9, 'day': 5}
{{Birth-date and age|3 November 1959}} -> {'year': 3, 'month': None, 'day': None}
{{Birth date|1923|3|28|df|=|yes}} -> {'year': 1923, 'month': 3, 'day': 28}
{{Birth date and age|1962|7|16}} -> {'year': 1962, 'month': 7, 'day': 16}
{{birth year and age|1983|07}} -> {'year': 1983, 'month': None, 'day': None}
{{birth date |1952|6|3}} -> {'year': 1952, 'month': 6, 'day': 3}
{{birth-date and age|1 November 1937}} -> {'year': 1, 'month': None, 'day': None}
{{birth date and age|1930|12|17}} -> {'year': 1930, 'month': 12, 'day': 17}
{{Birth date and age|1942|05|07}} -> {'year': 1942, 'month': 5, 'day': 7}
{{birth date and age|1975|04|09}} -> {'year': 1975, 'month': 4, 'day': 9}
{{birth date and age|1931|9|1}} -> {'year': 1931, 'month': 9, 'day': 1}
{{Birth date|1960|10|08|df|=|yes}} -> {'year': 1960, 'month': 10, 'day': 8}
{{Birth date|df|=|yes|1940|7|16}} -> {'year': 1940, 'month': 7, 'day': 16}
{{birth date and age|1955|05|19}} -> {'year': 1955, 'month': 5, 'day': 19}
{{Birth date and age|1946|02|24}} -> {'year': 1946, 'month': 2, 'day': 24}
{{birth date and age|1934|08|19}} -> {'year': 1934, 'month': 8, 'day': 19}
{{birth date|1938|12|03}} -> {'year': 1938, 'month': 12, 'day': 3}
{{birth date and age|1932|07|04}} -> {'year': 1932, 'month': 7, 'day': 4}
{{Birth date|1949|10|08|mf|=|y}} -> {'year': 1949, 'month': 10, 'day': 8}
{{Birth date|1941|6|28}} -> {'year': 1941, 'month': 6, 'day': 28}
{{Birth date and age|1942|7|20}} -> {'year': 1942, 'month': 7, 'day': 20}
{{birth based on age as of date |32 |2016|November}} -> {'year': 32, 'month': None, 'day': None}
{{Birth date and age|1957|10|15}} -> {'year': 1957, 'month': 10, 'day': 15}
8 October 1962 -> {'year': 1962, 'month': 10, 'day': 8}
{{birth date|df|=|y|1791|12|26}} -> {'year': 1791, 'month': 12, 'day': 26}
{{Birth year and age|1958}} -> {'year': 1958, 'month': None, 'day': None}
{{birth date and age|1948|10|1|df|=|y}} -> {'year': 1948, 'month': 10, 'day': 1}
{{Birth date and age|df|=|yes|1967|12|29}} -> {'year': 1967, 'month': 12, 'day': 29}
30 March 1925 -> {'year': 1925, 'month': 3, 'day': 30}
{{birth year and age|1961}} -> {'year': 1961, 'month': None, 'day': None}
{{birth date and age|1943|05|28}} -> {'year': 1943, 'month': 5, 'day': 28}
{{birth date and age|1979|5|29}} -> {'year': 1979, 'month': 5, 'day': 29}
{{Birth date and age|1946|9|6}} -> {'year': 1946, 'month': 9, 'day': 6}
{{birth date |1948|04|24 |df|=|yes}} -> {'year': 1948, 'month': 4, 'day': 24}
{{birth date and age|1981|11|23|mf|=|yes}} -> {'year': 1981, 'month': 11, 'day': 23}
24 May 1957 -> {'year': 1957, 'month': 5, 'day': 24}
December 25, 1985 -> {'year': 1985, 'month': 12, 'day': 25}
{{Birth date|mf|=|yes|1924|12|3}} -> {'year': 1924, 'month': 12, 'day': 3}
{{Birth date and age|1944|02|18}} -> {'year': 1944, 'month': 2, 'day': 18}
{{Birth date and age|df|=|yes|1956|03|12}} -> {'year': 1956, 'month': 3, 'day': 12}
{{birth date|1937|12|21|df|=|y}} -> {'year': 1937, 'month': 12, 'day': 21}
{{birth date and age|1934|08|03|mf|=|y}} -> {'year': 1934, 'month': 8, 'day': 3}
{{birth date and age|1964|3|5}} -> {'year': 1964, 'month': 3, 'day': 5}
{{birth year and age|1964}} -> {'year': 1964, 'month': None, 'day': None}
{{birth year and age|1956}} -> {'year': 1956, 'month': None, 'day': None}
{{birth date and age|1945|11|09}} -> {'year': 1945, 'month': 11, 'day': 9}
{{birth date|1931|11|20}} -> {'year': 1931, 'month': 11, 'day': 20}
{{Birth date and age|df|=|y|1966|8|26}} -> {'year': 1966, 'month': 8, 'day': 26}
{{birth date|1943|09|02|df|=|y}} -> {'year': 1943, 'month': 9, 'day': 2}
{{Birth date and age|1960|11|25}} {{citation needed|date|=|July 2013}} -> {'year': 1960, 'month': 11, 'day': 25}
{{Birth date and age|df|=|y|1947|10|8}} -> {'year': 1947, 'month': 10, 'day': 8}
January 1991 -> {'year': 1991, 'month': 1, 'day': None}
{{birth date|1956|3|15}} -> {'year': 1956, 'month': 3, 'day': 15}
1982 -> {'year': 1982, 'month': None, 'day': None}
{{birth date|1915|03|11}} -> {'year': 1915, 'month': 3, 'day': 11}
{{b-da|13 August 1960}} -> {'year': 1960, 'month': 8, 'day': 13}
{{birth date and age|1943|12|08}} -> {'year': 1943, 'month': 12, 'day': 8}
{{birth date and age|1937|11|27|df|=|no}} -> {'year': 1937, 'month': 11, 'day': 27}
{{Birth date and age|1968|06|07|df|=|yes}} -> {'year': 1968, 'month': 6, 'day': 7}
{{Birth year and age|1949}} -> {'year': 1949, 'month': None, 'day': None}
{{birth date and age|1953|02|20}} -> {'year': 1953, 'month': 2, 'day': 20}
{{birth date|1931|2|19|mf|=|y}} -> {'year': 1931, 'month': 2, 'day': 19}
October 10, 1961 -> {'year': 1961, 'month': 10, 'day': 10}
{{Birth date|1920|02|08}} -> {'year': 1920, 'month': 2, 'day': 8}
1943 -> {'year': 1943, 'month': None, 'day': None}
{{birth date and age|1967|02|02}} -> {'year': 1967, 'month': 2, 'day': 2}
{{Birth year and age|1938}} -> {'year': 1938, 'month': None, 'day': None}
{{birth date|mf|=|yes|1911|08|18}} -> {'year': 1911, 'month': 8, 'day': 18}
{{birth date and age|df|=|yes|1956|9|15}} -> {'year': 1956, 'month': 9, 'day': 15}
{{birth date|df|=|yes|1927|07|04}} -> {'year': 1927, 'month': 7, 'day': 4}
{{birth date and age|1945|12|31}} -> {'year': 1945, 'month': 12, 'day': 31}
1953 -> {'year': 1953, 'month': None, 'day': None}
{{birth date and age|1952|04|29|df|=|y}} -> {'year': 1952, 'month': 4, 'day': 29}
{{b-da|January 1968}} -> {'year': 1968, 'month': 1, 'day': None}
{{Birth date|1927|11|4}} -> {'year': 1927, 'month': 11, 'day': 4}
{{birth year and age |1946}} -> {'year': 1946, 'month': None, 'day': None}
1981 -> {'year': 1981, 'month': None, 'day': None}
{{birth date and age|1956|02|25}} -> {'year': 1956, 'month': 2, 'day': 25}
{{Birth date and age|1947|5|6|mf|=|y}} -> {'year': 1947, 'month': 5, 'day': 6}
{{Birth date and age|df|=|yes|1946|9|9}} -> {'year': 1946, 'month': 9, 'day': 9}
{{birth year and age|1959}} -> {'year': 1959, 'month': None, 'day': None}
{{birth date|df|=|yes|1949|12|22}} -> {'year': 1949, 'month': 12, 'day': 22}
{{birth year and age|1959}} -> {'year': 1959, 'month': None, 'day': None}
{{birth-date and age|4 July 1961}} -> {'year': 4, 'month': None, 'day': None}
{{birth date|1955|4|3|df|=|y}} -> {'year': 1955, 'month': 4, 'day': 3}
{{Birth date and age|df|=|yes|1965|05|04}} -> {'year': 1965, 'month': 5, 'day': 4}
1943 -> {'year': 1943, 'month': None, 'day': None}
December 13, 1937 -> {'year': 1937, 'month': 12, 'day': 13}
26 April 1934 -> {'year': 1934, 'month': 4, 'day': 26}
{{birth date and age |1939|12|29|mf|=|y}} -> {'year': 1939, 'month': 12, 'day': 29}
1972 -> {'year': 1972, 'month': None, 'day': None}
{{birth date and age|1961|4|9}} -> {'year': 1961, 'month': 4, 'day': 9}
{{Birth date|1949|1|17}} -> {'year': 1949, 'month': 1, 'day': 17}
{{birth year|1961}} -> {'year': 1961, 'month': None, 'day': None}
{{birth date and age |1949|05|16}} -> {'year': 1949, 'month': 5, 'day': 16}
{{birth date and age|1961|10|04}} -> {'year': 1961, 'month': 10, 'day': 4}
{{Birth date and age|1939|10|09}} -> {'year': 1939, 'month': 10, 'day': 9}
{{birth date and age|1948|6|18}} -> {'year': 1948, 'month': 6, 'day': 18}
{{Birth date and age|1926|12|03}} -> {'year': 1926, 'month': 12, 'day': 3}
{{birth date and age|1975|11|7|df|=|y}} -> {'year': 1975, 'month': 11, 'day': 7}
{{Birth date|1960|10|23}} -> {'year': 1960, 'month': 10, 'day': 23}
{{birth date|df|=|y|1935|8|26}} -> {'year': 1935, 'month': 8, 'day': 26}
{{birth date and age|df|=|yes|1970|02|08}} -> {'year': 1970, 'month': 2, 'day': 8}
{{birth year and age|1948}} -> {'year': 1948, 'month': None, 'day': None}
{{birth date and age|1948|03|23}} -> {'year': 1948, 'month': 3, 'day': 23}
{{Birth date and age|1931|5|29}} -> {'year': 1931, 'month': 5, 'day': 29}
{{birth date |1975|07|20}} -> {'year': 1975, 'month': 7, 'day': 20}
{{birth date and age|1943|12|23}} -> {'year': 1943, 'month': 12, 'day': 23}
{{birth date and age|1946|11|04}} -> {'year': 1946, 'month': 11, 'day': 4}
{{b-da|23 January 1947}} -> {'year': 1947, 'month': 1, 'day': 23}
{{Birth year and age|1953}} -> {'year': 1953, 'month': None, 'day': None}
{{Birth date and age|1966|06|27|mf|=|y}} -> {'year': 1966, 'month': 6, 'day': 27}
{{birth date and age|1932|07|31}} -> {'year': 1932, 'month': 7, 'day': 31}
{{birth date|df|=|yes|1931|01|23}} -> {'year': 1931, 'month': 1, 'day': 23}
{{birth date and age|mf |=|yes|1948|9|22}} -> {'year': 1948, 'month': 9, 'day': 22}
{{Birth date and age|1951|12|18}} -> {'year': 1951, 'month': 12, 'day': 18}
{{Birth date|1921|01|22}} -> {'year': 1921, 'month': 1, 'day': 22}
1958 -> {'year': 1958, 'month': None, 'day': None}
{{Birth date|1957|7|14|df|=|yes}} -> {'year': 1957, 'month': 7, 'day': 14}
{{birth date|mf|=|yes|1954|12|21}} -> {'year': 1954, 'month': 12, 'day': 21}
{{birth date|1936|10|4|mf|=|y}} -> {'year': 1936, 'month': 10, 'day': 4}
{{birth date and age|1952|7|6}} -> {'year': 1952, 'month': 7, 'day': 6}
{{Birth date and age|df|=|y|1963|2|24}} -> {'year': 1963, 'month': 2, 'day': 24}
{{birth date and age|1937|02|16|df|=|y}} -> {'year': 1937, 'month': 2, 'day': 16}
{{birth date|1921|2|4}} -> {'year': 1921, 'month': 2, 'day': 4}
{{birth date and age|1956|01|24}} -> {'year': 1956, 'month': 1, 'day': 24}
{{birth date|1929|2|2}} -> {'year': 1929, 'month': 2, 'day': 2}
{{birth date|1944|4|30}} -> {'year': 1944, 'month': 4, 'day': 30}
{{birth year and age|1947}} -> {'year': 1947, 'month': None, 'day': None}
{{birth date |1943|07|13 |df|=|y}} -> {'year': 1943, 'month': 7, 'day': 13}
October 22, 1918 -> {'year': 1918, 'month': 10, 'day': 22}
December 31, 1949 -> {'year': 1949, 'month': 12, 'day': 31}
1945 -> {'year': 1945, 'month': None, 'day': None}
{{birth year and age|1961}} -> {'year': 1961, 'month': None, 'day': None}
{{Birth date|1947|7|18|mf|=|y}} -> {'year': 1947, 'month': 7, 'day': 18}
{{Birth date and age|1946|8|30|mf|=|y}} -> {'year': 1946, 'month': 8, 'day': 30}
{{birth date and age|1973|5|13}} -> {'year': 1973, 'month': 5, 'day': 13}
{{birth date and age|1934|01|11|df|=|yes}} -> {'year': 1934, 'month': 1, 'day': 11}
{{birth date and age|1961|7|21|df|=|y}} -> {'year': 1961, 'month': 7, 'day': 21}
{{birth year and age|1969}} -> {'year': 1969, 'month': None, 'day': None}
{{Birth year and age|1932}} -> {'year': 1932, 'month': None, 'day': None}
{{birth year and age|1960}} -> {'year': 1960, 'month': None, 'day': None}
{{birth date |1954|08|23}} -> {'year': 1954, 'month': 8, 'day': 23}
{{birth date and age|df|=|yes|1971|10|18}} -> {'year': 1971, 'month': 10, 'day': 18}
{{birth date and age|df|=|y|1966|07|26}} -> {'year': 1966, 'month': 7, 'day': 26}
{{Birth date and age|1965|11|08}} -> {'year': 1965, 'month': 11, 'day': 8}
1954 -> {'year': 1954, 'month': None, 'day': None}
{{Birth date|1922|04|01}} -> {'year': 1922, 'month': 4, 'day': 1}
{{birth date|1953|09|12}} -> {'year': 1953, 'month': 9, 'day': 12}
{{birth date and age|1932|10|11}} -> {'year': 1932, 'month': 10, 'day': 11}
{{birth date and age|1959|1|1|df|=|y}} -> {'year': 1959, 'month': 1, 'day': 1}
{{birth date and age|1926|12|02|df|=|y}} -> {'year': 1926, 'month': 12, 'day': 2}
{{Birth date and age|df|=|yes|1955|08|03}} -> {'year': 1955, 'month': 8, 'day': 3}
{{birth date and age|df|=|yes|1964|01|10}} -> {'year': 1964, 'month': 1, 'day': 10}
{{Birth date and age|df|=|yes|1956|05|28}} -> {'year': 1956, 'month': 5, 'day': 28}
{{Birth date and age|1939|12|26|mf|=|y}} -> {'year': 1939, 'month': 12, 'day': 26}
{{birth-date |October 20 1932}} -> {'year': 20, 'month': None, 'day': None}
{{birth date |1947|05|09}} -> {'year': 1947, 'month': 5, 'day': 9}
{{birth date and age|df|=|yes|1975|01|18}} -> {'year': 1975, 'month': 1, 'day': 18}
{{birth date|1928|3|23}} -> {'year': 1928, 'month': 3, 'day': 23}
{{Birth-date|October 24, 1919}} -> {'year': 24, 'month': None, 'day': None}
{{Birth date|1943|02|05}} -> {'year': 1943, 'month': 2, 'day': 5}
{{Birth date and age|mf|=|yes|1954|10|02}} -> {'year': 1954, 'month': 10, 'day': 2}
1955 -> {'year': 1955, 'month': None, 'day': None}
{{birth date|1912|02|12|df|=|y}} -> {'year': 1912, 'month': 2, 'day': 12}
{{birth date and age|1978|12|4|df|=|y}} -> {'year': 1978, 'month': 12, 'day': 4}
{{birth year and age|1972}} -> {'year': 1972, 'month': None, 'day': None}
{{Birth date|1928|3|2|df|=|yes}} -> {'year': 1928, 'month': 3, 'day': 2}
{{Birth date and age|1962|8|5|mf|=|y}} -> {'year': 1962, 'month': 8, 'day': 5}
July 28, 1951 -> {'year': 1951, 'month': 7, 'day': 28}
{{Birth date and age|1939|12|08}} -> {'year': 1939, 'month': 12, 'day': 8}
{{Birth date and age|1935|6|7}} -> {'year': 1935, 'month': 6, 'day': 7}
{{Birth date and age|1981|1|17}} -> {'year': 1981, 'month': 1, 'day': 17}
{{birth-date|1955}} -> {'year': 1955, 'month': None, 'day': None}
{{Birth date and age|1961|11|09|df|=|y}} -> {'year': 1961, 'month': 11, 'day': 9}
1976 -> {'year': 1976, 'month': None, 'day': None}
{{Birth date and age|df|=|y|1953|8|25}} -> {'year': 1953, 'month': 8, 'day': 25}
{{birth date and age|df|=|yes|1966|09|12}} -> {'year': 1966, 'month': 9, 'day': 12}
{{Birth date|1962|1|16}} -> {'year': 1962, 'month': 1, 'day': 16}
May 5, 1926 -> {'year': 1926, 'month': 5, 'day': 5}
{{birth date and age|1942|10|28|df|=|yes}} -> {'year': 1942, 'month': 10, 'day': 28}
{{Birth date and age|1986|5|12}} -> {'year': 1986, 'month': 5, 'day': 12}
{{birth date and age|1957|10|5|df|=|y}} -> {'year': 1957, 'month': 10, 'day': 5}
1958 -> {'year': 1958, 'month': None, 'day': None}
24 December 1977 -> {'year': 1977, 'month': 12, 'day': 24}
{{Birth date and age|1960|08|02}} -> {'year': 1960, 'month': 8, 'day': 2}
August 22, 1943 -> {'year': 1943, 'month': 8, 'day': 22}
{{birth date|1935|2|9|df|=|y}} -> {'year': 1935, 'month': 2, 'day': 9}
{{Birth date|1946|03|18}} -> {'year': 1946, 'month': 3, 'day': 18}
{{birth date and age|1938|5|16}} -> {'year': 1938, 'month': 5, 'day': 16}
{{Birth date and age|1947|06|26}} -> {'year': 1947, 'month': 6, 'day': 26}
{{birth date |1939|5|9}} -> {'year': 1939, 'month': 5, 'day': 9}
{{birth date and age|1980|2|21|df|=|y}} -> {'year': 1980, 'month': 2, 'day': 21}
{{birth year|1960}} -> {'year': 1960, 'month': None, 'day': None}
September 14, 1966 -> {'year': 1966, 'month': 9, 'day': 14}
{{Birth date and age|1942|3|14}} -> {'year': 1942, 'month': 3, 'day': 14}
February 29, 1948 -> {'year': 1948, 'month': 2, 'day': 29}
{{birth year and age|1953}} -> {'year': 1953, 'month': None, 'day': None}
{{Birth year and age|1972}} -> {'year': 1972, 'month': None, 'day': None}
{{Birth year and age|1965}} -> {'year': 1965, 'month': None, 'day': None}
March 4, 1976 -> {'year': 1976, 'month': 3, 'day': 4}
{{birth date |1916|06|23}} -> {'year': 1916, 'month': 6, 'day': 23}
{{Birth date and age|1969|04|06|mf|=|yes}} -> {'year': 1969, 'month': 4, 'day': 6}
{{birth date|df|=|yes|1923|8|19}} -> {'year': 1923, 'month': 8, 'day': 19}
{{birth date |1965|6}} -> {'year': 1965, 'month': None, 'day': None}
{{birth date and age |1960|5|26|mf|=|yes}} -> {'year': 1960, 'month': 5, 'day': 26}
{{b-da|April 11, 1954}} -> {'year': 1954, 'month': 4, 'day': 11}
{{birth date|df|=|yes|1924|2|21}} -> {'year': 1924, 'month': 2, 'day': 21}
{{Birth date and age|1945|7|22}} -> {'year': 1945, 'month': 7, 'day': 22}
20 February 1944 -> {'year': 1944, 'month': 2, 'day': 20}
{{birth date and age|1942|7|26}} -> {'year': 1942, 'month': 7, 'day': 26}
{{Birth date and age|1954|10|15}} -> {'year': 1954, 'month': 10, 'day': 15}
{{birth date |1945|06|21 |df|=|yes}} -> {'year': 1945, 'month': 6, 'day': 21}
1950 -> {'year': 1950, 'month': None, 'day': None}
{{Birth date and age|1988|03|16|mf|=|yes}} -> {'year': 1988, 'month': 3, 'day': 16}
{{birth date and age|1948|9|10}} -> {'year': 1948, 'month': 9, 'day': 10}
1924 -> {'year': 1924, 'month': None, 'day': None}
{{birth year and age|1982}} -> {'year': 1982, 'month': None, 'day': None}
{{b-da|10 June 1965}} -> {'year': 1965, 'month': 6, 'day': 10}
{{birth date and age|1961|06|20}} -> {'year': 1961, 'month': 6, 'day': 20}
{{Birth date and age|1940|07|17}} -> {'year': 1940, 'month': 7, 'day': 17}
{{birth date |1929|12|21}} -> {'year': 1929, 'month': 12, 'day': 21}
{{Birth date and age|df|=|yes|1959|05|28}} -> {'year': 1959, 'month': 5, 'day': 28}
{{birth-date|1951}} -> {'year': 1951, 'month': None, 'day': None}
{{birth year and age|2000}} -> {'year': 2000, 'month': None, 'day': None}
{{birth date |1964|08|23}} -> {'year': 1964, 'month': 8, 'day': 23}
{{birth year and age|1971}} -> {'year': 1971, 'month': None, 'day': None}
{{birth date and age|1946|7|11}} -> {'year': 1946, 'month': 7, 'day': 11}
{{birth date|1968|08|17}} -> {'year': 1968, 'month': 8, 'day': 17}
{{Birth date and age|df|=|yes|1974|06|16}} -> {'year': 1974, 'month': 6, 'day': 16}
{{Birth date|1935|05|10}} -> {'year': 1935, 'month': 5, 'day': 10}
1966 -> {'year': 1966, 'month': None, 'day': None}

{{birth year and age|1962}} -> {'year': 1962, 'month': None, 'day': None}
{{birth year and age|1943}} -> {'year': 1943, 'month': None, 'day': None}
{{Birth date and age|1959|12|6|df|=|y}} -> {'year': 1959, 'month': 12, 'day': 6}
{{Birth date and age|df|=|yes|1954|12|30}} -> {'year': 1954, 'month': 12, 'day': 30}
1976 -> {'year': 1976, 'month': None, 'day': None}
{{birth date and age|1961|05|09}} -> {'year': 1961, 'month': 5, 'day': 9}
1944 -> {'year': 1944, 'month': None, 'day': None}
{{Birth date|1952|7|15}} -> {'year': 1952, 'month': 7, 'day': 15}
{{Birth month and age|1959|12}} -> {'year': 1959, 'month': None, 'day': 12}
{{Birth date and age|1927|9|8}} -> {'year': 1927, 'month': 9, 'day': 8}
{{Birth year and age|1983}} -> {'year': 1983, 'month': None, 'day': None}
{{Birth year and age|1944}} -> {'year': 1944, 'month': None, 'day': None}
{{Birth year and age|1980}} -> {'year': 1980, 'month': None, 'day': None}
{{Birth date and age|1963|6|14|mf|=|y}} -> {'year': 1963, 'month': 6, 'day': 14}
{{Birth date|1903|6|14}} -> {'year': 1903, 'month': 6, 'day': 14}
January 14, 1919 -> {'year': 1919, 'month': 1, 'day': 14}
{{Birth date and age|1974|01|04}} -> {'year': 1974, 'month': 1, 'day': 4}
{{birth date and age|1944|12|21}} -> {'year': 1944, 'month': 12, 'day': 21}
{{birth date|1932|07|25}} -> {'year': 1932, 'month': 7, 'day': 25}
{{birth date|1914|11|8}} -> {'year': 1914, 'month': 11, 'day': 8}
{{Birth date|1940|9|6}} -> {'year': 1940, 'month': 9, 'day': 6}
{{birth year and age|1970|7}} -> {'year': 1970, 'month': None, 'day': None}
{{Birth year and age|1951}} -> {'year': 1951, 'month': None, 'day': None}
{{birth date |1924|12|27}} -> {'year': 1924, 'month': 12, 'day': 27}
{{birth date|1945|08|12}} -> {'year': 1945, 'month': 8, 'day': 12}
{{birth date and age|1951|8|17}} -> {'year': 1951, 'month': 8, 'day': 17}
{{Birth year and age|1971}} -> {'year': 1971, 'month': None, 'day': None}
{{Birth date and age|1965|03|09|mf|=|y}} -> {'year': 1965, 'month': 3, 'day': 9}
{{birth date and age|df|=|yes|1961|07|20}} -> {'year': 1961, 'month': 7, 'day': 20}
{{birth date and age|mf|=|yes|1937|08|27}} -> {'year': 1937, 'month': 8, 'day': 27}
{{birth date and age|1937|01|26}} -> {'year': 1937, 'month': 1, 'day': 26}
{{birth date and age|1952|06|03}} -> {'year': 1952, 'month': 6, 'day': 3}
{{Birth date|1953|07|01|df|=|yes}} -> {'year': 1953, 'month': 7, 'day': 1}
{{Birth date|1925|03|01|df|=|yes}} -> {'year': 1925, 'month': 3, 'day': 1}
{{Birth date and age|1937|10|09}} -> {'year': 1937, 'month': 10, 'day': 9}
{{Birth date and age|1947|3|2|df|=|y}} -> {'year': 1947, 'month': 3, 'day': 2}
{{birth date and age|1953|11|13|df|=|yco}} -> {'year': 1953, 'month': 11, 'day': 13}
{{birth date and age|df|=|yes|1982|05|05}} -> {'year': 1982, 'month': 5, 'day': 5}
April 9, 1919 -> {'year': 1919, 'month': 4, 'day': 9}
{{Birth date and age|1975|5|30}} -> {'year': 1975, 'month': 5, 'day': 30}
{{Birth date|1933|4|23}} -> {'year': 1933, 'month': 4, 'day': 23}
{{b-da|August 1973}} -> {'year': 1973, 'month': 8, 'day': None}
{{birth year and age |1960}} -> {'year': 1960, 'month': None, 'day': None}
{{birth date and age|df|=|y|1928|10|14}} -> {'year': 1928, 'month': 10, 'day': 14}
{{birth date|1906|4|28}} -> {'year': 1906, 'month': 4, 'day': 28}
{{Birth date|1927|7|7}} -> {'year': 1927, 'month': 7, 'day': 7}
{{birth date and age|1962|05|17}} -> {'year': 1962, 'month': 5, 'day': 17}
{{b-da|November 12, 1959}} -> {'year': 1959, 'month': 11, 'day': 12}
{{birth date|1924|12|11}} -> {'year': 1924, 'month': 12, 'day': 11}
{{birth date and age|df|=|yes|1934|8|16}} -> {'year': 1934, 'month': 8, 'day': 16}
1965 -> {'year': 1965, 'month': None, 'day': None}
{{birth date and age|1929|1|3}} -> {'year': 1929, 'month': 1, 'day': 3}
{{birth date and age|df|=|yes|1933|07|11}} -> {'year': 1933, 'month': 7, 'day': 11}
{{Birth date and age|1944|03|16}} -> {'year': 1944, 'month': 3, 'day': 16}
{{birth year and age|1966}} -> {'year': 1966, 'month': None, 'day': None}
{{Birth date and age|1971|02|12|mf|=|y}} -> {'year': 1971, 'month': 2, 'day': 12}
{{Birth date and age|1982|01|14}} -> {'year': 1982, 'month': 1, 'day': 14}
{{birth date and age|1936|12|6}} -> {'year': 1936, 'month': 12, 'day': 6}
{{Birth year and age|1959}} -> {'year': 1959, 'month': None, 'day': None}
1963 -> {'year': 1963, 'month': None, 'day': None}
{{birth date |1952|07|22}} -> {'year': 1952, 'month': 7, 'day': 22}
{{b-da|6 May 1956}} -> {'year': 1956, 'month': 5, 'day': 6}
{{birth date and age|1953|10|25|mf|=|y}} -> {'year': 1953, 'month': 10, 'day': 25}
{{birth date and age|1958|10|14}} -> {'year': 1958, 'month': 10, 'day': 14}
{{birth-date|1938}} -> {'year': 1938, 'month': None, 'day': None}
{{birth date|1953|05|26|df|=|y}} -> {'year': 1953, 'month': 5, 'day': 26}
{{birth date and age |df|=|yes|1947|6|25}} -> {'year': 1947, 'month': 6, 'day': 25}
{{birth date and age|1955|09|18}} -> {'year': 1955, 'month': 9, 'day': 18}
1953 -> {'year': 1953, 'month': None, 'day': None}
{{Birth date|1922|3|2|mf|=|yes}} -> {'year': 1922, 'month': 3, 'day': 2}
March 23, 1953 -> {'year': 1953, 'month': 3, 'day': 23}
{{Birth date and age|1944|4|7|mf|=|y}} -> {'year': 1944, 'month': 4, 'day': 7}
{{Birth date and age|1981|12|9}} -> {'year': 1981, 'month': 12, 'day': 9}
{{birth date|1932|08|04}} -> {'year': 1932, 'month': 8, 'day': 4}
{{birth date|1972|6|21}} -> {'year': 1972, 'month': 6, 'day': 21}
{{Birth year and age|1945}} -> {'year': 1945, 'month': None, 'day': None}
{{Birth date and age|df|=|yes|1944|11|1}} -> {'year': 1944, 'month': 11, 'day': 1}
{{Birth date|1923|01|17|df|=|y}} -> {'year': 1923, 'month': 1, 'day': 17}
{{Birth date|df|=|yes|1916|12|09}} -> {'year': 1916, 'month': 12, 'day': 9}
{{birth date|1936|5|10}} -> {'year': 1936, 'month': 5, 'day': 10}
1944 -> {'year': 1944, 'month': None, 'day': None}
{{birth date|1925|5|30|mf|=|y}} -> {'year': 1925, 'month': 5, 'day': 30}
{{Birth date|1913|6|26|df|=|yes}} -> {'year': 1913, 'month': 6, 'day': 26}
{{birth year and age|1969}} -> {'year': 1969, 'month': None, 'day': None}
{{Birth date and age|1956|12|14|mf|=|y}} -> {'year': 1956, 'month': 12, 'day': 14}
{{birth date and age|1970|8|17}} -> {'year': 1970, 'month': 8, 'day': 17}
{{birth year and age |1975}} -> {'year': 1975, 'month': None, 'day': None}
17 January 1963 -> {'year': 1963, 'month': 1, 'day': 17}
{{Birth date and age|1960|3|19}} -> {'year': 1960, 'month': 3, 'day': 19}
{{Birth year and age|1954}} -> {'year': 1954, 'month': None, 'day': None}
{{Birth date and age|df|=|yes|1950|8|15}} -> {'year': 1950, 'month': 8, 'day': 15}
January 1984 -> {'year': 1984, 'month': 1, 'day': None}
{{birth date and age|1974|4|17}} -> {'year': 1974, 'month': 4, 'day': 17}
1961 -> {'year': 1961, 'month': None, 'day': None}
February 16, 1926 -> {'year': 1926, 'month': 2, 'day': 16}
{{birth date|1916|4|30}} -> {'year': 1916, 'month': 4, 'day': 30}
{{birth date and age|1966|5|27}} -> {'year': 1966, 'month': 5, 'day': 27}
January 17, 1492 -> {'year': None, 'month': 1, 'day': 17}
{{Birth year and age|1960}} -> {'year': 1960, 'month': None, 'day': None}
July 28, 1921 -> {'year': 1921, 'month': 7, 'day': 28}
{{Birth year and age|1982}} -> {'year': 1982, 'month': None, 'day': None}
{{Birth date and age|1947|7|10|mf|=|y}} -> {'year': 1947, 'month': 7, 'day': 10}
{{birth date and age|1951|8|9}} -> {'year': 1951, 'month': 8, 'day': 9}
{{Birth date and age|1952|9|22|mf|=|yes}} -> {'year': 1952, 'month': 9, 'day': 22}
{{Birth year and age|1957}} -> {'year': 1957, 'month': None, 'day': None}
{{birth date |1901|12|05}} -> {'year': 1901, 'month': 12, 'day': 5}
{{Birth date and age|1976|12|16|mf|=|y}} -> {'year': 1976, 'month': 12, 'day': 16}
{{birth year and age|1950}} -> {'year': 1950, 'month': None, 'day': None}
1971 -> {'year': 1971, 'month': None, 'day': None}
{{Birth date and age|1939|10|6|mf|=|y}} -> {'year': 1939, 'month': 10, 'day': 6}
{{birth date|1882|12|10|df|=|y}} -> {'year': 1882, 'month': 12, 'day': 10}
{{Birth year and age|1957}} -> {'year': 1957, 'month': None, 'day': None}
{{birth date |1977|11|02}} -> {'year': 1977, 'month': 11, 'day': 2}
{{Birth year and age|1971}} -> {'year': 1971, 'month': None, 'day': None}
{{Birth date and age|df|=|yes|1952|02|12}} -> {'year': 1952, 'month': 2, 'day': 12}
{{birth date and age|1951|11|07}} -> {'year': 1951, 'month': 11, 'day': 7}
{{birth date and age|1950|12|18}} -> {'year': 1950, 'month': 12, 'day': 18}
{{bya|1944}} -> {'year': 1944, 'month': None, 'day': None}
{{birth date and age|df|=|yes|1950|08|19}} -> {'year': 1950, 'month': 8, 'day': 19}
{{birth date and age|January 4, 1959}} -> {'year': 4, 'month': None, 'day': None}
1944 -> {'year': 1944, 'month': None, 'day': None}
August 24, 1950 -> {'year': 1950, 'month': 8, 'day': 24}
{{Birth date and age|df|=|y|1971|10|20}} -> {'year': 1971, 'month': 10, 'day': 20}
{{Birth date and age|1981|05|03|df|=|y}} -> {'year': 1981, 'month': 5, 'day': 3}
{{Birth date and age|1955|4|5|df|=|yes}} -> {'year': 1955, 'month': 4, 'day': 5}
{{Birth date and age|1958|2|14|df|=|yes}} -> {'year': 1958, 'month': 2, 'day': 14}
{{Birth date and age|1988|1|28|df|=|y}} -> {'year': 1988, 'month': 1, 'day': 28}
{{birth year and age|1959}} -> {'year': 1959, 'month': None, 'day': None}
{{Birth year and age|1974}} -> {'year': 1974, 'month': None, 'day': None}
{{birth date and age|1973|6|25|df|=|y}} -> {'year': 1973, 'month': 6, 'day': 25}
27 August 1962 -> {'year': 1962, 'month': 8, 'day': 27}
{{birth date and age|1982|1|20|df|=|y}} -> {'year': 1982, 'month': 1, 'day': 20}
{{birth date and age|1958|11|05}} -> {'year': 1958, 'month': 11, 'day': 5}
{{birth date and age|df|=|yes|1973|05|03}} -> {'year': 1973, 'month': 5, 'day': 3}
{{birth year and age|1970}} -> {'year': 1970, 'month': None, 'day': None}
{{Birth date and age|1936|07|17}} -> {'year': 1936, 'month': 7, 'day': 17}
{{birth date and age|df|=|yes|1945|10|16}} -> {'year': 1945, 'month': 10, 'day': 16}
{{Birth year and age|1951}} -> {'year': 1951, 'month': None, 'day': None}
{{birth date and age|1929|3|29}} -> {'year': 1929, 'month': 3, 'day': 29}
{{Birth date and age|df|=|yes|1985|11|14}} -> {'year': 1985, 'month': 11, 'day': 14}
{{Birth date and age|1949|12|20}} -> {'year': 1949, 'month': 12, 'day': 20}
1929 -> {'year': 1929, 'month': None, 'day': None}
1963 -> {'year': 1963, 'month': None, 'day': None}
2 August 1977 -> {'year': 1977, 'month': 8, 'day': 2}
1977-01-26 -> {'year': 1977, 'month': None, 'day': None}
{{Birth date|1954|03|11}} -> {'year': 1954, 'month': 3, 'day': 11}
1941 -> {'year': 1941, 'month': None, 'day': None}
October 31, 1934 -> {'year': 1934, 'month': 10, 'day': 31}
{{Birth date and age|1971|11|05|df|=|y}} -> {'year': 1971, 'month': 11, 'day': 5}
{{Birth date and age|1944|08|01|df|=|y}} -> {'year': 1944, 'month': 8, 'day': 1}
{{birth date and age|1971|03|07|df|=|y}} -> {'year': 1971, 'month': 3, 'day': 7}
1971 -> {'year': 1971, 'month': None, 'day': None}
November 16, 1939
Portland, Oregon -> {'year': 1939, 'month': 11, 'day': 16}
{{Birth date and age|df|=|yes|1963|3|1}} -> {'year': 1963, 'month': 3, 'day': 1}
{{Birth date and age|1964|05|31|df|=|y}} -> {'year': 1964, 'month': 5, 'day': 31}
{{Birth date and age|df|=|y|1963|4|25}} -> {'year': 1963, 'month': 4, 'day': 25}
{{Birth date and age|df|=|yes|1933|09|08}} -> {'year': 1933, 'month': 9, 'day': 8}
{{Birth date and age|1947|11|19|df|=|yes}} -> {'year': 1947, 'month': 11, 'day': 19}
{{Birth year and age|1944}} -> {'year': 1944, 'month': None, 'day': None}
20 June 1954 -> {'year': 1954, 'month': 6, 'day': 20}
{{birth date and age |1987|05|25|mf|=|yes}} -> {'year': 1987, 'month': 5, 'day': 25}
{{birth date and age|1967|08|06}} -> {'year': 1967, 'month': 8, 'day': 6}
{{birth-date|1967}} -> {'year': 1967, 'month': None, 'day': None}
{{Birth year and age|1951}} -> {'year': 1951, 'month': None, 'day': None}
{{birth date and age|1934|09|08}} -> {'year': 1934, 'month': 9, 'day': 8}
{{birth year and age|1983}} -> {'year': 1983, 'month': None, 'day': None}
June {{birth year and age|1962}} -> {'year': 1962, 'month': None, 'day': None}
{{birth date and age|1976|1|29|df|=|yes}} -> {'year': 1976, 'month': 1, 'day': 29}
{{Birth date and age|1936|10|31|df|=|y}} -> {'year': 1936, 'month': 10, 'day': 31}
{{Birth date and age|1955|3|1|df|=|yes}} -> {'year': 1955, 'month': 3, 'day': 1}
{{birth-date and age|3 August 1965}} -> {'year': 3, 'month': None, 'day': None}
{{birth date|1948|06|19|df|=|y}} -> {'year': 1948, 'month': 6, 'day': 19}
1972 or 1973 -> {'year': 1972, 'month': None, 'day': None}
{{birth date and age|1990|9|28}} -> {'year': 1990, 'month': 9, 'day': 28}
1959 -> {'year': 1959, 'month': None, 'day': None}
{{birth year and age|1975}} -> {'year': 1975, 'month': None, 'day': None}
{{birth date and age|df|=|yes|1977|03|24}} -> {'year': 1977, 'month': 3, 'day': 24}
{{birth date and age |df|=|yes|1978|10|27}} -> {'year': 1978, 'month': 10, 'day': 27}
1 April 1953 -> {'year': 1953, 'month': 4, 'day': 1}
{{Birth date and age|1965|05|16}} -> {'year': 1965, 'month': 5, 'day': 16}
{{birth date and age|1995|5|24|df|=|y}} -> {'year': 1995, 'month': 5, 'day': 24}
{{birth date and age|1957|12|31|df|=|y}} -> {'year': 1957, 'month': 12, 'day': 31}
{{Birth date and age|1953|3|12|df|=|yes}} -> {'year': 1953, 'month': 3, 'day': 12}
June 4th, 1963 -> {'year': 1963, 'month': 6, 'day': 4}
1986 -> {'year': 1986, 'month': None, 'day': None}
{{birth year and age|1969}} -> {'year': 1969, 'month': None, 'day': None}
{{Birth date and age|1943|11|9|df|=|y}} -> {'year': 1943, 'month': 11, 'day': 9}
{{birth date and age|df|=|yes|1961|07|03}} -> {'year': 1961, 'month': 7, 'day': 3}
{{birth year and age|1968}} -> {'year': 1968, 'month': None, 'day': None}
{{birth date and age|1953|10|18}} -> {'year': 1953, 'month': 10, 'day': 18}
{{Birth date and age|1983|12|07}} -> {'year': 1983, 'month': 12, 'day': 7}
1965 -> {'year': 1965, 'month': None, 'day': None}
{{birth date|1940|9|12}} -> {'year': 1940, 'month': 9, 'day': 12}
2 July 1926 -> {'year': 1926, 'month': 7, 'day': 2}
{{birth year and age|1967}} -> {'year': 1967, 'month': None, 'day': None}

In [23]:
with open("nice_birth_date_mapping.json",'w') as fd:
    json.dump(birth_mapping_arr, fd, indent=4)

In [24]:
attr_name="nationality"
for curr_elem in df:
    if attr_name in curr_elem:
        exp=curr_elem[attr_name]
        got=purify_nationality(exp)
        print(f"{exp} -> {got}\n######\n")
        print(type(got))
        print(len(got))

[[United States|American]] -> United States
######

<class 'str'>
13
German -> German
######

<class 'str'>
6
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
British -> British
######

<class 'str'>
7
British, American -> British, American
######

<class 'str'>
17
American -> American
######

<class 'str'>
8
{{flag|United States}} ->
######

<class 'str'>
0
[[Australian]] -> Australian
######

<class 'str'>
10
American -> American
######

<class 'str'>
8
[[United States|American]] -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
British -> British
######

<class 'str'>
7
[[United States|American]] -> United States
######

<class 'str'>
13
Canada -> Canada
######

<class 'str'>
6
Indian-American -> Indian-American
######

<class 'str'>
15
[[United States|American]] -> United States
######

<class 'str'>
13
[[Germany|German]] -> Germany
######

<class 'str'>
7
[[United States]] -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
[[United States|American]] -> United States
######

<class 'str'>
13
German -> German
######

<class 'str'>
6
British -> British
######

<class 'str'>
7
German -> German
######

<class 'str'>
6
Israeli -> Israeli
######

<class 'str'>
7
[[Americans|American]] -> Americans
######

<class 'str'>
9
[[United States|American]] -> United States
######

<class 'str'>
13
[[Romanian American]] -> Romanian American
######

<class 'str'>
17
Greek -> Greek
######

<class 'str'>
5
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
[[Netherlands|Dutch]] -> Netherlands
######

<class 'str'>
11
American <br> Israeli -> American ,  Israeli
######

<class 'str'>
19
American -> American
######

<class 'str'>
8
American, Canadian -> American, Canadian
######

<class 'str'>
18
Canadian -> Canadian
######

<class 'str'>
8
[[Germans|German]] -> Germans
######

<class 'str'>
7
United States -> United States
######

<class 'str'>
13
[[Greece|Greek]]-[[United States|American]] -> Greece-United States
######

<class 'str'>
20
[[Poland|Polish]] -> Poland
######

<class 'str'>
6
[[Hungary|Hungarian]]-[[Americans|American]] -> Hungary-Americans
######

<class 'str'>
17
American -> American
######

<class 'str'>
8
[[United States|American]] -> United States
######

<class 'str'>
13
[[United States|American]] -> United States
######

<class 'str'>
13
British -> British
######

<class 'str'>
7
American -> American
######

<class 'str'>
8
Spanish -> Spanish
######

<class 'str'>
7
British, American -> British, American
######

<class 'str'>
17
United States -> United States
######

<class 'str'>
13
[[United States|American]] -> United States
######

<class 'str'>
13
[[United States|American]] -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
[[United States|American]] -> United States
######

<class 'str'>
13
Russian -> Russian
######

<class 'str'>
7
United States -> United States
######

<class 'str'>
13
British -> British
######

<class 'str'>
7
[[Netherlands|Dutch]] -> Netherlands
######

<class 'str'>
11
American -> American
######

<class 'str'>
8
[[United States]] -> United States
######

<class 'str'>
13
[[American people|American]] -> American people
######

<class 'str'>
15
British -> British
######

<class 'str'>
7
[[Netherlands|Dutch]], [[United States|American]] -> Netherlands, United States
######

<class 'str'>
26
[[Portugal|Portuguese]] -> Portugal
######

<class 'str'>
8
[[United Kingdom|English]] -> United Kingdom
######

<class 'str'>
14
American -> American
######

<class 'str'>
8
[[Americans|American]] -> Americans
######

<class 'str'>
9
[[United States of America|American]] -> United States of America
######

<class 'str'>
24
{{flag|USA}} ->
######

<class 'str'>
0
[[United States]] -> United States
######

<class 'str'>
13
British -> British
######

<class 'str'>
7
Chinese -> Chinese
######

<class 'str'>
7
American -> American
######

<class 'str'>
8
[[Americans|American]] -> Americans
######

<class 'str'>
9
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
Canada -> Canada
######

<class 'str'>
6
[[Israel]]i -> Israeli
######

<class 'str'>
7
[[United Kingdom|British]] -> United Kingdom
######

<class 'str'>
14
American -> American
######

<class 'str'>
8
[[Germany|German]] -> Germany
######

<class 'str'>
7
[[United States|American]] -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
Iranian -> Iranian
######

<class 'str'>
7
[[United States|American]] -> United States
######

<class 'str'>
13
USA -> USA
######

<class 'str'>
3
[[United States|American]] -> United States
######

<class 'str'>
13
United States -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
[[Pakistani people | Pakistani]] -> Pakistani people
######

<class 'str'>
17
[[Chinese people|Chinese]] -> Chinese people
######

<class 'str'>
14
American -> American
######

<class 'str'>
8
French<br>Turkish -> French, Turkish
######

<class 'str'>
15
American -> American
######

<class 'str'>
8
[[United States|American]] -> United States
######

<class 'str'>
13
[[Syrian American]] -> Syrian American
######

<class 'str'>
15
American -> American
######

<class 'str'>
8
[[Americans|American]] -> Americans
######

<class 'str'>
9
[[US|American, Israeli]] -> US
######

<class 'str'>
2
{{hlist|Hungarian|American}} ->
######

<class 'str'>
0
[[Americans|American]] -> Americans
######

<class 'str'>
9
American -> American
######

<class 'str'>
8
[[Brazilian-American]] -> Brazilian-American
######

<class 'str'>
18
American -> American
######

<class 'str'>
8
[[Canadians|Canadian]] and [[Americans|American]] -> Canadians and Americans
######

<class 'str'>
23
United States -> United States
######

<class 'str'>
13
Israeli -> Israeli
######

<class 'str'>
7
United States -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
[[Germany|German]] -> Germany
######

<class 'str'>
7
English -> English
######

<class 'str'>
7
[[Denmark|Danish]] -> Denmark
######

<class 'str'>
7
American -> American
######

<class 'str'>
8
[[United States|American]] -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
[[United States|American]] -> United States
######

<class 'str'>
13
[[Israel]]i -> Israeli
######

<class 'str'>
7
American -> American
######

<class 'str'>
8
Canadian -> Canadian
######

<class 'str'>
8
[[USA]] -> USA
######

<class 'str'>
3
U.S. -> U.S.
######

<class 'str'>
4
[[Americans|American]] -> Americans
######

<class 'str'>
9
English -> English
######

<class 'str'>
7
German -> German
######

<class 'str'>
6
American -> American
######

<class 'str'>
8
Argentinian -> Argentinian
######

<class 'str'>
11
Swiss -> Swiss
######

<class 'str'>
5
[[United States|American]] -> United States
######

<class 'str'>
13
[[United States|American]] -> United States
######

<class 'str'>
13
German -> German
######

<class 'str'>
6
American [[computer scientist]] -> American computer scientist
######

<class 'str'>
27
French -> French
######

<class 'str'>
6
American -> American
######

<class 'str'>
8
Chinese-American -> Chinese-American
######

<class 'str'>
16
British -> British
######

<class 'str'>
7
[[United States|American]] -> United States
######

<class 'str'>
13
[[Russia]]n -> Russian
######

<class 'str'>
7
American -> American
######

<class 'str'>
8
[[United States|American]] -> United States
######

<class 'str'>
13
[[Russians|Russian]] -> Russians
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
[[Image:Flag of the United States.svg|20px|]] [[United States]] -> Image:Flag of the United States.svg United States
######

<class 'str'>
49
[[Spain]] -> Spain
######

<class 'str'>
5
French -> French
######

<class 'str'>
6
{{hlist|Hungarian|American}} ->
######

<class 'str'>
0
British -> British
######

<class 'str'>
7
American -> American
######

<class 'str'>
8
[[Netherlands|Dutch]] -> Netherlands
######

<class 'str'>
11
[[Israel]]i -> Israeli
######

<class 'str'>
7
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
Canadian -> Canadian
######

<class 'str'>
8
German -> German
######

<class 'str'>
6
[[United States]] -> United States
######

<class 'str'>
13
British -> British
######

<class 'str'>
7
French -> French
######

<class 'str'>
6
Israeli-American -> Israeli-American
######

<class 'str'>
16
Irish, American -> Irish, American
######

<class 'str'>
15
American -> American
######

<class 'str'>
8
[[Norway]] -> Norway
######

<class 'str'>
6
[[United States|American]] -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
[[United States|American]] -> United States
######

<class 'str'>
13
[[United States|American]] -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
[[Americans|American]] -> Americans
######

<class 'str'>
9
British -> British
######

<class 'str'>
7
[[United States|American]] -> United States
######

<class 'str'>
13
United States -> United States
######

<class 'str'>
13
[[Australia]]n -> Australian
######

<class 'str'>
10
[[United States|American]] -> United States
######

<class 'str'>
13
British -> British
######

<class 'str'>
7
[[Romania|Romanian]] -> Romania
######

<class 'str'>
7
American -> American
######

<class 'str'>
8
[[Uruguay]]an, [[Canadians|Canadian]], [[Switzerland|Swiss]] -> Uruguayan, Canadians, Switzerland
######

<class 'str'>
33
American -> American
######

<class 'str'>
8
United States -> United States
######

<class 'str'>
13
Italian -> Italian
######

<class 'str'>
7
American -> American
######

<class 'str'>
8
Japanese -> Japanese
######

<class 'str'>
8
[[Russia]]n -> Russian
######

<class 'str'>
7
United States -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
[[United States]] -> United States
######

<class 'str'>
13
[[United States|American]] -> United States
######

<class 'str'>
13
[[United States|American]] -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
{{flag icon|United States}} [[United States]] ->  United States
######

<class 'str'>
14
Canadian, Egyptian -> Canadian, Egyptian
######

<class 'str'>
18
British -> British
######

<class 'str'>
7
Nigerian -> Nigerian
######

<class 'str'>
8
Indian -> Indian
######

<class 'str'>
6
American -> American
######

<class 'str'>
8
British -> British
######

<class 'str'>
7
[[Americans|American]] -> Americans
######

<class 'str'>
9
American -> American
######

<class 'str'>
8
[[Netherlands|Dutch]] -> Netherlands
######

<class 'str'>
11
New Zealand -> New Zealand
######

<class 'str'>
11
[[United States|American]] -> United States
######

<class 'str'>
13
French -> French
######

<class 'str'>
6
[[United States|American]] -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
[[Hungarians|Hungarian]] -> Hungarians
######

<class 'str'>
10
[[Latvian people|Latvian]] -> Latvian people
######

<class 'str'>
14
American -> American
######

<class 'str'>
8
[[United States|American]] -> United States
######

<class 'str'>
13
{{USA}} ->
######

<class 'str'>
0
[[Israel]] -> Israel
######

<class 'str'>
6
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
[[United States|American]] -> United States
######

<class 'str'>
13
[[United States|American]] -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
[[United States|American]] -> United States
######

<class 'str'>
13
[[Israelis|Israeli]] -> Israelis
######

<class 'str'>
8
[[United States]] -> United States
######

<class 'str'>
13
[[Argentina]] -> Argentina
######

<class 'str'>
9
USA -> USA
######

<class 'str'>
3
American -> American
######

<class 'str'>
8
[[United States|American]] citizen -> United States citizen
######

<class 'str'>
21
[[Switzerland|Swiss]], [[Canadians|Canadian]] -> Switzerland, Canadians
######

<class 'str'>
22
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
[[India]]n, [[United States|American]] -> Indian, United States
######

<class 'str'>
21
[[France|French]] -> France
######

<class 'str'>
6
British -> British
######

<class 'str'>
7
[[United States]] -> United States
######

<class 'str'>
13
[[Turkish people|Turkish]]-[[Serbians|Serbian]] -> Turkish people-Serbians
######

<class 'str'>
23
United States -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
[[United Kingdom|British]] -> United Kingdom
######

<class 'str'>
14
{{Plainlist|
*[[Israelis|Israeli]]
*[[United States nationality law|American]]}} -> {{PlainlistIsraelis
*United States nationality law}}
######

<class 'str'>
52
[[Image:Flag of Belgium.svg|20px|]] [[Belgium|Belgian]] -> Image:Flag of Belgium.svg Belgium
######

<class 'str'>
33
American -> American
######

<class 'str'>
8
[[United States]] -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
[[United States|American]] -> United States
######

<class 'str'>
13
Australian/British -> Australian/British
######

<class 'str'>
18
Israel -> Israel
######

<class 'str'>
6
American -> American
######

<class 'str'>
8
[[United States|American]] -> United States
######

<class 'str'>
13
[[United States]] -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
Romanian -> Romanian
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
Hungarian -> Hungarian
######

<class 'str'>
9
American -> American
######

<class 'str'>
8
Spanish / Lebanese -> Spanish / Lebanese
######

<class 'str'>
18
American -> American
######

<class 'str'>
8
German -> German
######

<class 'str'>
6
American -> American
######

<class 'str'>
8
Israel -> Israel
######

<class 'str'>
6
[[United Kingdom|British]] -> United Kingdom
######

<class 'str'>
14
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
[[United States|American]] -> United States
######

<class 'str'>
13
[[American people|American]] -> American people
######

<class 'str'>
15
American -> American
######

<class 'str'>
8
Dutch -> Dutch
######

<class 'str'>
5
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
United States -> United States
######

<class 'str'>
13
[[Australian]] -> Australian
######

<class 'str'>
10
[[United States]] -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
Senegalese -> Senegalese
######

<class 'str'>
10
[[Canadians|Canadian]] -> Canadians
######

<class 'str'>
9
[[Australia]]n -> Australian
######

<class 'str'>
10
[[Germany|German]] and [[United States|American]] -> Germany and United States
######

<class 'str'>
25
[[United States|American]] -> United States
######

<class 'str'>
13
[[Slovakia|Slovak]] -> Slovakia
######

<class 'str'>
8
[[Romania]]n -> Romanian
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
[[Romanian American|Romanian-American]] -> Romanian American
######

<class 'str'>
17
American -> American
######

<class 'str'>
8
[[United States|American]] -> United States
######

<class 'str'>
13
United States -> United States
######

<class 'str'>
13
[[Americans|American]] -> Americans
######

<class 'str'>
9
American -> American
######

<class 'str'>
8
Pakistani -> Pakistani
######

<class 'str'>
9
[[United States|American]] -> United States
######

<class 'str'>
13
[[United States|American]] -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
United States -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
Dutch -> Dutch
######

<class 'str'>
5
[[Bulgaria]]n -> Bulgarian
######

<class 'str'>
9
{{USSR}} <br /> {{UKR}} ->  ,
######

<class 'str'>
4
[[United States]] -> United States
######

<class 'str'>
13
United States -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
[[Norway|Norwegian]] -> Norway
######

<class 'str'>
6
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
[[United Kingdom|British]] -> United Kingdom
######

<class 'str'>
14
[[United States|American]] -> United States
######

<class 'str'>
13
German -> German
######

<class 'str'>
6
[[Image:Flag of Sweden.svg|20px]] [[Sweden|Swedish]] -> Image:Flag of Sweden.svg Sweden
######

<class 'str'>
31
[[United States]] -> United States
######

<class 'str'>
13
[USA] -> USA
######

<class 'str'>
3
[[Indian American]] -> Indian American
######

<class 'str'>
15
Australian -> Australian
######

<class 'str'>
10
American -> American
######

<class 'str'>
8
New Zealand -> New Zealand
######

<class 'str'>
11
American -> American
######

<class 'str'>
8
English -> English
######

<class 'str'>
7
[[France|French]] -> France
######

<class 'str'>
6
American -> American
######

<class 'str'>
8
Danish -> Danish
######

<class 'str'>
6
[[United States|American]] -> United States
######

<class 'str'>
13
[[United States|American]] -> United States
######

<class 'str'>
13
United States -> United States
######

<class 'str'>
13
[[Israel]]i -> Israeli
######

<class 'str'>
7
American -> American
######

<class 'str'>
8
French -> French
######

<class 'str'>
6
British -> British
######

<class 'str'>
7
[[Americans|American]] -> Americans
######

<class 'str'>
9
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
United States -> United States
######

<class 'str'>
13
German -> German
######

<class 'str'>
6
[[Jamaica]] -> Jamaica
######

<class 'str'>
7
Indian -> Indian
######

<class 'str'>
6
[[United States|American]] -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
[[United States|American]] -> United States
######

<class 'str'>
13
Irish, American -> Irish, American
######

<class 'str'>
15
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
German -> German
######

<class 'str'>
6
[[United States|American]] -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
[[France|French]] -> France
######

<class 'str'>
6
German -> German
######

<class 'str'>
6
Austrian -> Austrian
######

<class 'str'>
8
[[United States|U.S.]] [[Image:Flag of the United States.svg|20px|]] -> United States Image:Flag of the United States.svg
######

<class 'str'>
49
[[France|French]] -> France
######

<class 'str'>
6
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
USA -> USA
######

<class 'str'>
3
American -> American
######

<class 'str'>
8
British -> British
######

<class 'str'>
7
American -> American
######

<class 'str'>
8
[[Americans|American]] -> Americans
######

<class 'str'>
9
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
Indian -> Indian
######

<class 'str'>
6
[[Belgians|Belgian]] -> Belgians
######

<class 'str'>
8
[[Italy|Italian]], [[US|American]] -> Italy, US
######

<class 'str'>
9
American -> American
######

<class 'str'>
8
German -> German
######

<class 'str'>
6
American -> American
######

<class 'str'>
8
[[France|French]] -> France
######

<class 'str'>
6
American -> American
######

<class 'str'>
8
[[Spain|Spanish]]-[[Argentine]] -> Spain-Argentine

<class 'str'>
13
American -> American
######

<class 'str'>
8
[[Americans|United States]] -> Americans
######

<class 'str'>
9
German -> German
######

<class 'str'>
6
[[United States|American]] -> United States
######

<class 'str'>
13
[[Israelis|Israeli]] -> Israelis
######

<class 'str'>
8
United States -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
[[United States|American]] -> United States
######

<class 'str'>
13
[[Germany|German]] -> Germany
######

<class 'str'>
7
American -> American
######

<class 'str'>
8
German -> German
######

<class 'str'>
6
[[United Kingdom|English]] -> United Kingdom
######

<class 'str'>
14
American -> American
######

<class 'str'>
8
[[United States|American]] -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
Finnish -> Finnish
######

<class 'str'>
7
Irish -> Irish
######

<class 'str'>
5
American -> American
######

<class 'str'>
8
USA -> USA
######

<class 'str'>
3
American -> American
######

<class 'str'>
8
Swiss [[Image:Flag of Switzerland.svg|20px|]] -> Swiss Image:Flag of Switzerland.svg
######

<class 'str'>
35
United States -> United States
######

<class 'str'>
13
{{Flagicon|Netherlands}} Dutch ->  Dutch
######

<class 'str'>
6
[[Singaporean]] -> Singaporean
######

<class 'str'>
11
[[United States|American]] -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
[[United States]] -> United States
######

<class 'str'>
13
[[United States]] -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
British (English) -> British (English)
######

<class 'str'>
17
[[United States|American]] -> United States
######

<class 'str'>
13
Polish -> Polish
######

<class 'str'>
6
American -> American
######

<class 'str'>
8
Canadian -> Canadian
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
[[India]]n <br> [[United States|American]] -> Indian ,  United States
######

<class 'str'>
23
Greek -> Greek
######

<class 'str'>
5
Japanese -> Japanese
######

<class 'str'>
8
[[United States|American]] -> United States
######

<class 'str'>
13
United States -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
Swiss American -> Swiss American
######

<class 'str'>
14
[[United Kingdom|Scottish]] -> United Kingdom
######

<class 'str'>
14
American -> American
######

<class 'str'>
8
[[United States|American]] -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
British -> British
######

<class 'str'>
7
Finnish (by birth)<br />American (naturalized) -> Finnish (by birth), American (naturalized)
######

<class 'str'>
42
[[French people|French]] -> French people
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
[[United Kingdom]] -> United Kingdom
######

<class 'str'>
14
American -> American
######

<class 'str'>
8
[[United States|American]] -> United States
######

<class 'str'>
13
USA -> USA
######

<class 'str'>
3
English -> English
######

<class 'str'>
7
Swedish / American -> Swedish / American
######

<class 'str'>
18
USA -> USA
######

<class 'str'>
3
Syrian -> Syrian
######

<class 'str'>
6
[[People of the United States|American]] -> People of the United States
######

<class 'str'>
27
[[United States|American]] -> United States
######

<class 'str'>
13
[[United States]] -> United States
######

<class 'str'>
13
Hungarian -> Hungarian
######

<class 'str'>
9
American -> American
######

<class 'str'>
8
Iranian-American -> Iranian-American
######

<class 'str'>
16
United States -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
Canadian -> Canadian
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
Danish -> Danish
######

<class 'str'>
6
British -> British
######

<class 'str'>
7
[[German-American]] -> German-American
######

<class 'str'>
15
Israeli -> Israeli
######

<class 'str'>
7
[[United States|American]] -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
[[United States|American]] -> United States
######

<class 'str'>
13
[[Polish American]] -> Polish American
######

<class 'str'>
15
Canadian -> Canadian
######

<class 'str'>
8
Canadian<br />British -> Canadian, British
######

<class 'str'>
17
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
French, American -> French, American
######

<class 'str'>
16
Italian -> Italian
######

<class 'str'>
7
United States of America -> United States of America
######

<class 'str'>
24
[[People of the United States|American]] -> People of the United States
######

<class 'str'>
27
American -> American
######

<class 'str'>
8
[[United States|American]] -> United States
######

<class 'str'>
13
[[United States|American]] -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
United States -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
Australian -> Australian
######

<class 'str'>
10
German -> German
######

<class 'str'>
6
Australian -> Australian
######

<class 'str'>
10
American -> American
######

<class 'str'>
8
[[United States|American]] -> United States
######

<class 'str'>
13
[[Image:Flag of the United States.svg|20px]] [[United States|U.S.]] -> Image:Flag of the United States.svg United States
######

<class 'str'>
49
American -> American
######

<class 'str'>
8
[[Americans|American]] -> Americans
######

<class 'str'>
9
[[People of the United States|American]] -> People of the United States
######

<class 'str'>
27
[[Finland|Finnish]] -> Finland
######

<class 'str'>
7
United States -> United States
######

<class 'str'>
13
[[Swiss American]] -> Swiss American
######

<class 'str'>
14
Italian -> Italian
######

<class 'str'>
7
[[Canadian]] -> Canadian
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
[[Israelis|Israeli]] -> Israelis
######

<class 'str'>
8
United States -> United States
######

<class 'str'>
13
[[United States|American]] -> United States
######

<class 'str'>
13
Australia -> Australia
######

<class 'str'>
9
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
[[United States of America|American]] -> United States of America
######

<class 'str'>
24
[[Belgian]] -> Belgian
######

<class 'str'>
7
American -> American
######

<class 'str'>
8
United States -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
Israel -> Israel
######

<class 'str'>
6
American -> American
######

<class 'str'>
8
British -> British
######

<class 'str'>
7
United States -> United States
######

<class 'str'>
13
[[Americans|American]] -> Americans
######

<class 'str'>
9
American -> American
######

<class 'str'>
8
USA -> USA
######

<class 'str'>
3
United States -> United States
######

<class 'str'>
13
Canadian -> Canadian
######

<class 'str'>
8
Italian -> Italian
######

<class 'str'>
7
[[United States]]<br/>[[Pakistan]] -> United States, Pakistan
######

<class 'str'>
23
United Kingdom -> United Kingdom
######

<class 'str'>
14
American -> American
######

<class 'str'>
8
Israeli -> Israeli
######

<class 'str'>
7
United States -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
[[United States|American]] -> United States
######

<class 'str'>
13
United States -> United States
######

<class 'str'>
13
American [[Switzerland|Swiss]] -> American Switzerland
######

<class 'str'>
20
American -> American
######

<class 'str'>
8
[[United States]] -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
[[United States|American]] -> United States
######

<class 'str'>
13
[[United States|American]] -> United States
######

<class 'str'>
13
[[United States|American]] -> United States
######

<class 'str'>
13
Israeli -> Israeli
######

<class 'str'>
7
[[United States]] -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
[[Americans|American]] -> Americans
######

<class 'str'>
9
Australian -> Australian
######

<class 'str'>
10
US Citizen -> US Citizen
######

<class 'str'>
10
USA -> USA
######

<class 'str'>
3
[[Australian]] -> Australian
######

<class 'str'>
10
[[Switzerland|Swiss]], [[Germany|German]] -> Switzerland, Germany
######

<class 'str'>
20
France -> France
######

<class 'str'>
6
[[Australia|Australian]] -> Australia
######

<class 'str'>
9
United States -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
[[Netherlands|Dutch]] -> Netherlands
######

<class 'str'>
11
American -> American
######

<class 'str'>
8
[[United States]] -> United States
######

<class 'str'>
13
[[United States|American]] -> United States
######

<class 'str'>
13
French -> French
######

<class 'str'>
6
Romanian -> Romanian
######

<class 'str'>
8
American, Polish -> American, Polish
######

<class 'str'>
16
Soviet<br>Russian -> Soviet, Russian
######

<class 'str'>
15
[[Australia]] -> Australia
######

<class 'str'>
9
Austrian -> Austrian
######

<class 'str'>
8
Indian -> Indian
######

<class 'str'>
6
Israeli-American -> Israeli-American
######

<class 'str'>
16
American -> American
######

<class 'str'>
8
[[US|American]] -> US
######

<class 'str'>
2
[[United States|American]] -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
{{flagicon|US}} [[US|American]] ->  US
######

<class 'str'>
3
[[United States|American]] -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
Dutch {{citation needed|date|=|November 2020}} / American -> Dutch  / American
######

<class 'str'>
17
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
[[Americans|American]]<br> [[Pakistanis|Pakistani]] -> Americans,  Pakistanis
######

<class 'str'>
22
American -> American
######

<class 'str'>
8
German -> German
######

<class 'str'>
6
American -> American
######

<class 'str'>
8
[[Germany]] -> Germany
######

<class 'str'>
7
[[Argentina|Argentine]]-[[United States|American]] -> Argentina-United States
######

<class 'str'>
23
[[United States]] -> United States
######

<class 'str'>
13
{{flagicon|Greece}} [[Greece]] ->  Greece
######

<class 'str'>
7
[[United States|American]] -> United States
######

<class 'str'>
13
[[United States|American]] -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
[[Italy|Italian]] -> Italy
######

<class 'str'>
5
India -> India
######

<class 'str'>
5
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
British -> British
######

<class 'str'>
7
American -> American
######

<class 'str'>
8
[[United States|American]] -> United States
######

<class 'str'>
13
German -> German
######

<class 'str'>
6
American -> American
######

<class 'str'>
8
{{flag|Australia}} ->
######

<class 'str'>
0
Icelandic -> Icelandic
######

<class 'str'>
9
Australian -> Australian
######

<class 'str'>
10
[[South Africa|South African]] -> South Africa
######

<class 'str'>
12
American -> American
######

<class 'str'>
8
American -> American
######

<class 'str'>
8
[[Germany|German]] -> Germany
######

<class 'str'>
7
American -> American
######

<class 'str'>
8
[[United States|American]] -> United States
######

<class 'str'>
13
United States -> United States
######

<class 'str'>
13
[[United States|American]] -> United States
######

<class 'str'>
13
American -> American
######

<class 'str'>
8
[[Germans|German]], [[Australian]] -> Germans, Australian
######

<class 'str'>
19
American -> American
######

<class 'str'>
8
Indian -> Indian
######

<class 'str'>
6
[[People's Republic of China]] -> People's Republic of China
######

<class 'str'>
26
American -> American
######

<class 'str'>
8
Indian -> Indian
######

<class 'str'>
6
{{flagicon|India}} [[India]]n ->  Indian
######

<class 'str'>
7
Chinese-American -> Chinese-American
######

<class 'str'>
16
[[Indian people|Indian]] -> Indian people
######

<class 'str'>
13
[[India]]n -> Indian
######

<class 'str'>
6
Indian, American -> Indian, American
######

<class 'str'>
16
Jamaican -> Jamaican
######

<class 'str'>
8
[[India]]n -> Indian
######

<class 'str'>
6
[[India]]n -> Indian
######

<class 'str'>
6
Chilean -> Chilean
######

<class 'str'>
7
German -> German
######

<class 'str'>
6
[[American nationality|American]] -> American nationality
######

<class 'str'>
20
[[United States|American]] -> United States
######

<class 'str'>
13
Indian -> Indian
######

<class 'str'>
6
Indian -> Indian
######

<class 'str'>
6
[[Canadian]] -> Canadian
######

<class 'str'>
8
[[India|Indian]] -> India
######

<class 'str'>
5
Egyptian -> Egyptian
######

<class 'str'>
8
Guinean -> Guinean
######

<class 'str'>
7
Bulgarian -> Bulgarian
######

<class 'str'>
9
American/Canadian -> American/Canadian
######

<class 'str'>
17
Belgian -> Belgian
######

<class 'str'>
7
[[File:Flag of Taiwan.svg|20px]] [[Taiwan]] -> File:Flag of Taiwan.svg Taiwan
######

<class 'str'>
30
[[India]]n -> Indian
######

<class 'str'>
6
[[Croatia]]n -> Croatian
######

<class 'str'>
8
[[India]]n -> Indian
######

<class 'str'>
6
Indian -> Indian
######

<class 'str'>
6
Indian -> Indian
######

<class 'str'>
6
[[Nepalis|Nepalese]] -> Nepalis
######

<class 'str'>
7
[[Greece]] -> Greece
######

<class 'str'>
6
Indian -> Indian
######

<class 'str'>
6
Bangladeshi/American/Canadian -> Bangladeshi/American/Canadian
######

<class 'str'>
29
[[India]]n -> Indian
######

<class 'str'>
6
Indian -> Indian
######

<class 'str'>
6
[[India]] -> India
######

<class 'str'>
5
Indian -> Indian
######

<class 'str'>
6
Indian -> Indian
######

<class 'str'>
6
American -> American
######

<class 'str'>
8
[[India]]n -> Indian
######

<class 'str'>
6
[[India]]n -> Indian
######

<class 'str'>
6
Indian -> Indian
######

<class 'str'>
6
Greek, British -> Greek, British
######

<class 'str'>
14
Portuguese -> Portuguese
######

<class 'str'>
10
[[Somalis|Somali]] -> Somalis
######

<class 'str'>
7
[[Switzerland|Swiss]] -> Switzerland
######

<class 'str'>
11
[[Iran]] -> Iran
######

<class 'str'>
4
American -> American
######

<class 'str'>
8
Argentinian -> Argentinian
######

<class 'str'>
11
[[Indian nationality|Indian]] -> Indian nationality
######

<class 'str'>
18

In [25]:
df[0]

{'pageid': 4210106,
 'url': 'https://en.wikipedia.org/wiki/Abraham_Silberschatz',
 'links': ['ACM Fellow',
  'Bell Labs',
  'C. Mohan',
  'Computer Science',
  'Computer scientist',
  'Database System Concepts',
  'Database systems',
  'Doctoral advisor',
  'Google Scholar',
  'Haifa, Israel',
  'ISNI (identifier)',
  'Operating systems',
  'RERO (identifier)',
  'Raghu Ramakrishnan',
  'Research',
  'SUDOC (identifier)',
  'State University of New York',
  'Stony Brook University',
  'University of texas at austin',
  'VIAF (identifier)',
  'Yale University'],
 'aliases': ['Avi Silberschatz'],
 'label': 'Abraham Silberschatz',
 'title': 'Abraham_Silberschatz',
 'image': 'Avi silberschatz.jpg',
 'backlinks': ['Database',
  'Windows 2000',
  'Process (computing)',
  'Program counter',
  'Memory management',
  'Scheduling (computing)',
  'Round-robin scheduling',
  'Two-phase locking',
  'Join (SQL)',
  'Page table',
  'Slab allocation',
  'Multivalued dependency',
  'List of Stony Brook University people',
  'Global serializability',
  'Kernel (operating system)',
  'C. Mohan',
  'Talk:Abraham Silberschatz',
  'User:Tony Sidaway/Living people/tranche 082',
  'User:Dingo1729/History of commitment ordering',
  'Database System Concepts',
  'User:Ibon.coria/sandbox',
  "Wikipedia:Administrators' noticeboard/IncidentArchive822",
  'User:Rebone System/sandbox',
  'User:H@r@ld/opensyllabus',
  'List of fellows of the Association for Computing Machinery',
  'User talk:Tom29739/Archive 27',
  'User:Oshwah/TalkPageArchives/2017-06',
  'User talk:Tom29739/Archive 30',
  'User talk:Tom29739/Archive 32',
  'User talk:Tom29739/Archive 34',
  'User talk:Tom29739/Archive 36',
  'User talk:Tom29739/Archive 38',
  'User talk:Tom29739/Archive 39',
  'User talk:Tom29739/Archive 43',
  'User talk:Tom29739/Archive 45',
  'File:Database System Concepts.jpg'],
 'categories': ['Category:American computer scientists',
  'Category:American computer specialist stubs',
  'Category:Fellow Members of the IEEE',
  'Category:Fellows of the Association for Computing Machinery',
  'Category:Living people',
  'Category:Stony Brook University alumni',
  'Category:Yale University faculty'],
 'ire_person_name': 'Abraham Silberschatz',
 'ire_wiki_id': 0,
 'name': 'Avi Silberschatz',
 'field': '[[Computer Science]]',
 'work_institution': '[[Yale University]]',
 'alma_mater': '[[Stony Brook University]]<br />[[Yale University]]',
 'doctoral_advisor': 'Arthur Bernstein<br>Richard Kieburtz',
 'doctoral_students': '[[C. Mohan]]<br>[[Raghu Ramakrishnan]]',
 'known_for': '[[database systems]]<br>[[operating systems]]',
 'prizes': 'ACM Fellow<br>IEEE Fellow<br>AAAS Fellow<br>IEEE Taylor L. Booth Education Award (2002)<br>ACM Karl V. Karlstrom Outstanding Educator Award (1998)<br>ACM SIGMOD Contribution Award (1997)<br> 2019 VLDB Test of Time Award',
 'website': 'http://www.cs.yale.edu/~avi/',
 'sex or gender (P21)': 'male (Q6581097)',
 'occupation (P106)': ['computer scientist (Q82594)', 'engineer (Q81096)'],
 'given name (P735)': 'Abraham (Q17997608)',
 'member of (P463)': 'Institute of Electrical and Electronics Engineers (Q131566)',
 'employer (P108)': 'Yale University (Q49112)',
 'country of citizenship (P27)': 'United States of America (Q30)',
 'educated at (P69)': ['Stony Brook University (Q969850)',
  'State University of New York (Q1140241)',
  'IDF Junior Command Preparatory Boarding School (Q7063325)'],
 'Library of Congress authority ID (P244)': 'n82162524',
 'Mathematics Genealogy Project ID (P549)': '94554',
 'languages spoken, written or signed (P1412)': 'English (Q1860)',
 'award received (P166)': ['ACM Fellow (Q18748039)', 'IEEE Fellow (Q111734)'],
 'doctoral student (P185)': ['C. Mohan (Q5006716)',
  'Raghu Ramakrishnan (Q7282986)',
  'Rajeev Rastogi (Q15995420)',
  'Donald Spencer Fussell (Q102129368)',
  'Iyer Venkateshwaran Ramakrishnan (Q102157550)',
  'Sharad Mehrotra (Q102196909)',
  'Samuel Lycurgus Grier, Jr. (Q102300750)',
  'Sumit Ganguly (Q102300751)',
  'Ernest Samuel Cohen (Q102300752)',
  'Khien Mien Chew (Q102300753)',
  'Banu Rahime Ozden (Q102300754)',
  'Robert Lee Read (Q102300755)'],
 'student (P802)': 'Kenneth Seals-Nutt (Q47487399)',
 'place of birth (P19)': 'Haifa (Q41621)',
 'official website (P856)': 'http://www.cs.yale.edu/~avi/',
 'WorldCat Identities ID (P7859)': 'lccn-n82162524',
 'doctoral advisor (P184)': ['Arthur Jay Bernstein (Q102077480)',
  'Richard Kieburtz (Q68622015)'],
 'Freebase ID (P646)': '/m/0bq3td',
 'date of birth (P569)': '+1947-05-01T00:00:00Z'}

In [26]:
from all_funcs import *
from purify_functions import *

In [27]:
examples=dict()

In [28]:
for curr_elem in master_mapping:
    examples[curr_elem['attr_name']]=[]

In [29]:
detailed_arr[0]

{'attr_name': 'pageid',
 'freq': 3469,
 'sample': 4210106,
 'parent_attr': '',
 'func': None}

In [30]:
from copy import deepcopy
for curr_key_obj in master_mapping:
    key_name=curr_key_obj['attr_name']
    examples[key_name]=[]
    if curr_key_obj['func']!=None:
        print("found func")
        for curr_elem in df:
            if key_name in curr_elem:
                to_push=curr_elem[key_name]
                org_val=to_push
                mod_val=curr_key_obj['func'](org_val)
                examples[key_name].append(deepcopy([org_val, mod_val]))

found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func
found func

In [31]:
with open("inspect_perform.json",'w') as fd:
    json.dump(examples, fd, indent=4)

In [32]:
purify_date_of_birth("+1938-11-13T00:00:00Z")

{'year': 1938, 'month': 11, 'day': 13}

In [33]:
get_univs_from_alma_mater("[[MIT]]<br>")

['MIT']

In [34]:
tc="{{Plainlist|\n\n* [[University of Bradford]] (BEng)\n\n* [[London School of Economics]] (MSc)\n\n* [[Royal College of Art]] (PhD)|ref| name=\"who\"}}"

In [35]:
get_univs_from_alma_mater(tc)

['University of Bradford',
 'London School of Economics',
 'Royal College of Art']

In [36]:
with open("purified_child_to_par_wiki.json",'r') as fd:
    df=json.load(fd)

In [37]:
def find_relevant_func(key_name):
    for idx, elem in enumerate(master_mapping):
        if elem['attr_name']==key_name:
            return elem['func']
    assert(False)
    return None

In [38]:
def find_relevant_key(key_name):
    for idx, elem in enumerate(master_mapping):
        if elem['attr_name']==key_name:
            if elem['parent_attr']=="":
                return key_name
            else:
                return elem['parent_attr']
    assert(False)
    return None

In [39]:
from copy import deepcopy

In [40]:
new_df=[]

In [41]:
for curr_elem in df:
    new_elem=dict()
    for curr_key in curr_elem:
        f_to_use=find_relevant_func(curr_key)
        if f_to_use!=None:
            #print(curr_key)
            #print(curr_elem[curr_key])
            curr_elem[curr_key]=f_to_use(curr_elem[curr_key])
        main_key=find_relevant_key(curr_key)
        if main_key in new_elem:
            if type(curr_elem[curr_key])!=list:
                    curr_elem[curr_key]=[curr_elem[curr_key]]
            if type(new_elem[main_key])==list:
                new_elem[main_key].extend(deepcopy(curr_elem[curr_key]))
            else:
                new_elem[main_key]=[new_elem[main_key]]
                new_elem[main_key].extend(deepcopy(curr_elem[curr_key]))                
        else:
            new_elem[main_key]=deepcopy(curr_elem[curr_key])
        if type(new_elem[main_key])==list:
            try:
                new_elem[main_key]=list(set(new_elem[main_key]))
            except:
                pass
    new_df.append(deepcopy(new_elem))

In [42]:
new_df[11]

{'wikipedia_page_id': 649298,
 'wikipedia_page_url': 'https://en.wikipedia.org/wiki/Jack_Dongarra',
 'wiki_pages_accessible_from_person_wiki_page': ['Yusuf Hamied',
  'Linear algebra',
  'American Association for the Advancement of Science',
  'HPCG',
  'LAPACK',
  'Texas A&M University',
  'John Rodenburg',
  'University of New Mexico',
  'Society for Industrial and Applied Mathematics',
  'School of Mathematics, University of Manchester',
  'Martin Embley',
  'Oak Ridge National Laboratory',
  'Steve A. Kay',
  'Royal Society',
  'Marta Kwiatkowska',
  'Akkihebbal Ravishankara',
  'IEEE Medal of Excellence in Scalable Computing',
  'Maple (software)',
  'Matthew Rushworth',
  'Foreign Member of the Russian Academy of Science',
  'Chicago State University',
  'CiteSeerX (identifier)',
  'Rice University',
  'Association for Computing Machinery',
  'Christine Orengo',
  'S2CID (identifier)',
  'Anne Osbourn',
  'Matthew Hurles',
  'Numerical algorithm',
  'University of Manchester',
  'Bachelor of Science',
  'Leonid Sazanov',
  'Institute of Electrical and Electronics Engineers',
  'Barbara Sherwood Lollar',
  'Gareth H. McKinley',
  'Anant Parekh',
  'Master of Science',
  'Message Passing Interface',
  'Doi (identifier)',
  'Mark Mayer',
  'DBLP',
  'Peter A. Butler',
  'Gagandeep Kang',
  'Kumar Wickramasinghe',
  'Elaine Fuchs',
  'Automatically Tuned Linear Algebra Software',
  'Julian Peto',
  'Robert Tibshirani',
  'Douglass Turnbull',
  'ISBN (identifier)',
  'IEEE Charles Babbage Award',
  'SIAM Fellow',
  'Sarah Darby',
  'Computer Science',
  'Molly Shoichet',
  'ACM Fellow',
  'International Parallel and Distributed Processing Symposium',
  'University of Tennessee',
  'Mathematics Genealogy Project',
  'ISNI (identifier)',
  'Scopus',
  'TOP500',
  'Gregory D. Scholes',
  'Performance Application Programming Interface',
  'Barry Barish',
  'Richard Jozsa',
  'John-Michael Kendall',
  "SIAM Special Interest Group on Supercomputing's award for Career Achievement",
  'Thesis',
  'Member of the National Academy of Engineering',
  'National Academy of Engineering',
  'Caucher Birkar',
  'Mark Handley (computer scientist)',
  'VIAF (identifier)',
  'Akshay Venkatesh',
  'IEEE Computer Pioneer Award',
  'EISPACK',
  'George Davey Smith',
  'Sandra Díaz (ecologist)',
  'Lucy Carpenter',
  'ScaLAPACK',
  'R (programming language)',
  'Foreign Member of the Royal Society',
  'James Briscoe',
  'Benjamin Blencowe',
  'Paraskevas Sphicas',
  'Fellow',
  'Cleve Moler',
  'Martin Head-Gordon',
  'Richard Harland (biologist)',
  'ORCID (identifier)',
  'David G. Nicholls',
  'LINPACK',
  'Ken Kennedy Award',
  'Illinois Institute of Technology',
  'SciPy',
  'Christopher Hacon',
  'Doctoral advisor',
  'Brian Staskawicz',
  'Ian Tomlinson (scientist)',
  'Roy Kerr',
  'IEEE Sid Fernbach Award',
  'Russian Academy of Sciences',
  'SIAM/ACM Prize in Computational Science and Engineering',
  'Jonathan C. Knight',
  'Bernie Fanaroff',
  'Fellow of the Royal Society',
  'SUDOC (identifier)',
  'Gurdyal Besra',
  'Liz Sockett',
  'Fellow of the American Association for the Advancement of Science',
  'Manjul Bhargava',
  'Jack W. Szostak',
  'Parallel Virtual Machine',
  'Inez Fung',
  'Argonne National Laboratory',
  'Charles Bangham',
  'Computational science',
  'Parallel computing',
  'IEEE Fellow',
  'Netlib',
  'GNU Octave',
  'Doctor of Philosophy',
  'Véronique Gouverneur',
  'Hans Clevers',
  'MATLAB',
  'James Rothman',
  'Basic Linear Algebra Subprograms',
  'Salim Abdool Karim',
  'Jonathan Flint (scientist)',
  'Wolfram Mathematica',
  'Peter H. Haynes',
  'David Milstein',
  'Andrew D. Taylor',
  'Applied Mathematics',
  'Caetano Reis e Sousa',
  'List of Fellows of the Royal Society elected in 2019',
  'Google Scholar'],
 'person_name': [{'pageid': 20354027, 'ns': 0, 'title': 'Jack J. Dongarra'},
  {'pageid': 24932849, 'ns': 0, 'title': 'J. J. Dongarra'},
  'Jack J. Dongarra',
  'Jack Dongarra',
  'Jack_Dongarra',
  'Jack Dongarra',
  'Jack',
  'Dongarra'],
 'person_image_links': [],
 'iwlinks': ['https://commons.wikimedia.org/wiki/Jack_Dongarra'],
 'backlinks_to_other_wiki_pages': ['Yusuf Hamied',
  'July 18',
  'Vera Kublanovskaya',
  'LAPACK',
  'Reduced instruction set computer',
  'List of numerical libraries',
  'Tianhe-2',
  'John Rodenburg',
  'K computer',
  'Martin Embley',
  'Oak Ridge National Laboratory',
  'Steve A. Kay',
  'LINPACK benchmarks',
  'Marta Kwiatkowska',
  'Akkihebbal Ravishankara',
  'Matthew Rushworth',
  'Cell (microprocessor)',
  'Christine Orengo',
  'Anne Osbourn',
  'Matthew Hurles',
  'Numerical linear algebra',
  'List of fellows of the Association for Computing Machinery',
  'Leonid Sazanov',
  'Integer relation algorithm',
  'List of fellows of the Royal Society D, E, F',
  'Barbara Sherwood Lollar',
  'Gareth H. McKinley',
  'Anant Parekh',
  'Matrix multiplication algorithm',
  'Computer Pioneer Award',
  'Self-tuning',
  'Message Passing Interface',
  'Template:FRS 2019',
  'Mark Mayer',
  'Peter A. Butler',
  'Gagandeep Kang',
  'Kumar Wickramasinghe',
  'Talk:LINPACK',
  'Elaine Fuchs',
  'Julian Peto',
  'Michela Taufer',
  'Robert Tibshirani',
  'Douglass Turnbull',
  'Helaman Ferguson',
  'Sidney Fernbach Award',
  'Sarah Darby',
  'Talk:Massively parallel',
  'Molly Shoichet',
  'International Parallel and Distributed Processing Symposium',
  'List of computer scientists',
  'TOP500',
  'HPCG benchmark',
  'Gregory D. Scholes',
  'Barry Barish',
  'Richard Jozsa',
  'John-Michael Kendall',
  'Caucher Birkar',
  'Mark Handley (computer scientist)',
  'General-purpose computing on graphics processing units',
  'Department of Mathematics, University of Manchester',
  'Sunway (processor)',
  'Akshay Venkatesh',
  'OpenCL',
  'EISPACK',
  'George Davey Smith',
  'Sandra Díaz (ecologist)',
  'Lucy Carpenter',
  'James Briscoe',
  'Benjamin Blencowe',
  'Paraskevas Sphicas',
  'Hans Meuer',
  'Cleve Moler',
  'Martin Head-Gordon',
  'Richard Harland (biologist)',
  'David G. Nicholls',
  'LINPACK',
  'J. J. Dongarra',
  'Ken Kennedy Award',
  'Christopher Hacon',
  'Cray-2',
  'John G. F. Francis',
  'Brian Staskawicz',
  'Ian Tomlinson (scientist)',
  'Roy Kerr',
  'List of University of New Mexico alumni',
  'SETI@home',
  'Jonathan C. Knight',
  'List of Illinois Institute of Technology alumni',
  'Talk:Jack Dongarra',
  'Bernie Fanaroff',
  'List of University of Tennessee people',
  'Gurdyal Besra',
  'Liz Sockett',
  'Manjul Bhargava',
  'Jack W. Szostak',
  'Inez Fung',
  'Computer',
  'Department of Computer Science, University of Manchester',
  'Charles Bangham',
  'Jack J. Dongarra',
  'Véronique Gouverneur',
  'Hans Clevers',
  'James Rothman',
  'List of fellows of the Royal Society elected in 2019',
  'Tony Hey',
  'Salim Abdool Karim',
  'Jonathan Flint (scientist)',
  'Peter H. Haynes',
  'David Milstein',
  'Supercomputing in Japan',
  'Intel iPSC',
  'Andrew D. Taylor',
  'List of Chicago State University people',
  'Caetano Reis e Sousa',
  'List of people by Erdős number',
  'Draft:Supercomputing Frontiers Europe'],
 'wikipedia_categories_associated_with': ['Academics of the University of Manchester',
  'Foreign Members of the Royal Society',
  'American computer scientists',
  'Rice University staff',
  'Fellows of the Society for Industrial and Applied Mathematics',
  'Foreign Members of the Russian Academy of Sciences',
  'Illinois Institute of Technology alumni',
  'Living people',
  'Members of the United States National Academy of Engineering',
  'Fellow Members of the IEEE',
  'Fellows of the American Association for the Advancement of Science',
  'Fellows of the Association for Computing Machinery',
  'People associated with the Department of Computer Science, University of Manchester',
  '1950 births',
  'Oak Ridge National Laboratory people',
  'University of Tennessee faculty'],
 'ire_person_name': 'Jack Dongarra',
 'ire_wiki_id': 11,
 'person_dob': [{'year': 1950, 'month': 7, 'day': 18},
  {'year': 1950, 'month': 7, 'day': 18}],
 'person_birth_place': 'Chicago',
 'country_of_citizenship': ['American / United States',
  'United States of America'],
 'person_nationality': 'American',
 'person_domains': ['Computer Science',
  'Parallel computing',
  'EISPACK, LINPACK, Basic Linear Algebra Subprograms, LAPACK, ScaLAPACK, Netlib, Parallel Virtual Machine, Message Passing Interface, NetSolve, TOP500, Automatically Tuned Linear Algebra Software, and Performance Application Programming Interface.',
  'Computational science'],
 'employer_orgs': ['University of Tennessee, Knoxville',
  'University of New Mexico',
  'Rice University',
  'University of Tennessee',
  'Argonne National Laboratory',
  'Oak Ridge National Laboratory',
  'University of Manchester'],
 'institutions_educated_in': ['Chicago State University (BSc)',
  'Illinois Institute of Technology (MSc)',
  'University of New Mexico',
  'University of New Mexico (PhD)',
  'Illinois Institute of Technology'],
 'doctoral advisor(s)': ['Cleve Moler'],
 'person_thesis': 'Improving the Accuracy of Computed Matrix Eigenvalues',
 'thesis_url': 'http://search.proquest.com/docview/303029334',
 'thesis_year': '1980',
 'awards_received': ['SIAM Fellow (2009)',
  'Member of the National Academy of Engineering (2001)',
  'AAAS Fellow',
  'Fellow of the American Association for the Advancement of Science (1994) (FAAAS)',
  'IEEE Fellow (1999)',
  'Sidney Fernbach Award',
  'IEEE Fellow',
  'IEEE Charles Babbage Award (2011)',
  'Foreign Member of the Royal Society',
  'Foreign Member of the Royal Society (2019)',
  'IEEE Sid Fernbach Award (2004)',
  'Fellow of the Society for Industrial and Applied Mathematics',
  "SIAM Special Interest Group on Supercomputing's award for Career Achievement (2010)",
  'SIAM/ACM Prize in Computational Science and Engineering (2019)',
  'ACM Fellow',
  'Ken Kennedy Award',
  'IEEE Computer Pioneer Award (2020)',
  'Foreign Member of the Russian Academy of Science (2017)',
  'ACM Fellow (2001)',
  'IEEE Medal of Excellence in Scalable Computing (2008)',
  'ACM/IEEE Ken Kennedy Award (2013)'],
 'associated_website': ['{{URL|http://www.netlib.org/utk/people/JackDongarra}}',
  'http://www.netlib.org/utk/people/JackDongarra/'],
 'person_gender': 'male',
 'Mathematics Genealogy Project ID (P549)': '14931',
 'Freebase ID (P646)': '/m/02_g_s',
 'person_job': ['computer scientist',
  'university teacher',
  'engineer',
  'mathematician'],
 'member of (P463)': ['Royal Society',
  'Society for Industrial and Applied Mathematics',
  'Institute of Electrical and Electronics Engineers',
  'Association for Computing Machinery',
  'US National Academy of Engineering'],
 'place_of_birth': 'Chicago',
 'Google Scholar author ID (P1960)': 'X4SbSTAAAAAJ',
 'person_notable_work': 'EISPACK',
 'Library of Congress authority ID (P244)': 'n79058186',
 'WorldCat Identities ID (P7859)': 'lccn-n79058186',
 'person_residence': 'United States of America',
 'languages spoken, written or signed': 'English',
 'person_doctoral_students': ['James B. White',
  'David Eberius',
  'Tingxing Tim Dong',
  'Yulu Jia',
  'Chongxiao Cao',
  'Yaohung Mike Tsai',
  'Zizhong Chen',
  'Camille Coti',
  'Blake Haugen',
  'Thananon Patinyasakdikul',
  'Khairul Kabir',
  'Xi Luo',
  'Reazul Hoque',
  'Piotr Luszczek',
  'Peng Du',
  'Mohammad Majed Sidani',
  'Asim YarKhan',
  'Antoine Paul Petitet',
  'Heike Jagode',
  'Sathish Vadhiyar',
  'Wei Wu',
  'Haihang You',
  'Thara Angskun',
  'Fengguang Song',
  'Lorie M. Liebrock',
  'Erika Fuentes',
  'Teng Ma',
  'Jelena Pjesivac-Grbovic',
  'Youngbae Kim',
  'Wesley Bland',
  'Zhiao Shi',
  'Henri Casanova']}

In [43]:
with open("cleaned_merged_par_child_wiki.json",'w') as fd:
    json.dump(new_df, fd, indent=4)